/*----- PROTECTED REGION ID(NewPort8742CtrlClass.cpp) ENABLED START -----*/
static const char *RcsId      = "$Id:  $";
static const char *TagName    = "$Name:  $";
static const char *CvsPath    = "$Source:  $";
static const char *SvnPath    = "$HeadURL:  $";
static const char *HttpServer = "http://www.esrf.eu/computing/cs/tango/tango_doc/ds_doc/";
//=============================================================================
//
// file :        NewPort8742CtrlClass.cpp
//
// description : C++ source for the NewPort8742CtrlClass. A singleton
//               class derived from DeviceClass. It implements the
//               command list and all properties and methods required
//               by the «name» once per process.
//
// project :     NewPort8742Ctrl.
//
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// SVN only:
// $HeadURL:  $
//
// CVS only:
// $Source:  $
// $Log:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <NewPort8742CtrlClass.h>

/*----- PROTECTED REGION END -----*/	//	NewPort8742CtrlClass.cpp

//-------------------------------------------------------------------
/**
 *	Create NewPort8742CtrlClass singleton and
 *	return it in a C function for Python usage
 */
//-------------------------------------------------------------------
extern "C" {
#ifdef _TG_WINDOWS_

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_NewPort8742Ctrl_class(const char *name) {
		return NewPort8742Ctrl_ns::NewPort8742CtrlClass::init(name);
	}
}

namespace NewPort8742Ctrl_ns
{
//===================================================================
//	Initialize pointer for singleton pattern
//===================================================================
NewPort8742CtrlClass *NewPort8742CtrlClass::_instance = NULL;

//--------------------------------------------------------
/**
 * method : 		NewPort8742CtrlClass::NewPort8742CtrlClass(string &s)
 * description : 	constructor for the NewPort8742CtrlClass
 *
 * @param s	The class name
 */
//--------------------------------------------------------
NewPort8742CtrlClass::NewPort8742CtrlClass(string &s):Tango::DeviceClass(s)
{
	cout2 << "Entering NewPort8742CtrlClass constructor" << endl;
	set_default_property();
	write_class_property();

	/*----- PROTECTED REGION ID(NewPort8742CtrlClass::constructor) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	NewPort8742CtrlClass::constructor

	cout2 << "Leaving NewPort8742CtrlClass constructor" << endl;
}

//--------------------------------------------------------
/**
 * method : 		NewPort8742CtrlClass::~NewPort8742CtrlClass()
 * description : 	destructor for the NewPort8742CtrlClass
 */
//--------------------------------------------------------
NewPort8742CtrlClass::~NewPort8742CtrlClass()
{
	/*----- PROTECTED REGION ID(NewPort8742CtrlClass::destructor) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	NewPort8742CtrlClass::destructor

	_instance = NULL;
}


//--------------------------------------------------------
/**
 * method : 		NewPort8742CtrlClass::init
 * description : 	Create the object if not already done.
 *                  Otherwise, just return a pointer to the object
 *
 * @param	name	The class name
 */
//--------------------------------------------------------
NewPort8742CtrlClass *NewPort8742CtrlClass::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new NewPort8742CtrlClass(s);
		}
		catch (bad_alloc &)
		{
			throw;
		}
	}
	return _instance;
}

//--------------------------------------------------------
/**
 * method : 		NewPort8742CtrlClass::instance
 * description : 	Check if object already created,
 *                  and return a pointer to the object
 */
//--------------------------------------------------------
NewPort8742CtrlClass *NewPort8742CtrlClass::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}



//===================================================================
//	Command execution method calls
//===================================================================
//--------------------------------------------------------
/**
 * method : 		WriteClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *WriteClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "WriteClass::execute(): arrived" << endl;
	Tango::DevString argin;
	extract(in_any, argin);
	((static_cast<NewPort8742Ctrl *>(device))->write(argin));
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		WriteReadStringClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *WriteReadStringClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "WriteReadStringClass::execute(): arrived" << endl;
	Tango::DevString argin;
	extract(in_any, argin);
	return insert((static_cast<NewPort8742Ctrl *>(device))->write_read_string(argin));
}

//--------------------------------------------------------
/**
 * method : 		WriteReadLongClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *WriteReadLongClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "WriteReadLongClass::execute(): arrived" << endl;
	Tango::DevString argin;
	extract(in_any, argin);
	return insert((static_cast<NewPort8742Ctrl *>(device))->write_read_long(argin));
}

//--------------------------------------------------------
/**
 * method : 		ResetClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *ResetClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "ResetClass::execute(): arrived" << endl;
	((static_cast<NewPort8742Ctrl *>(device))->reset());
	return new CORBA::Any();
}


//===================================================================
//	Properties management
//===================================================================
//--------------------------------------------------------
/**
 *	Method      : NewPort8742CtrlClass::get_class_property()
 *	Description : Get the class property for specified name.
 */
//--------------------------------------------------------
Tango::DbDatum NewPort8742CtrlClass::get_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, returns  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : NewPort8742CtrlClass::get_default_device_property()
 *	Description : Return the default value for device property.
 */
//--------------------------------------------------------
Tango::DbDatum NewPort8742CtrlClass::get_default_device_property(string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : NewPort8742CtrlClass::get_default_class_property()
 *	Description : Return the default value for class property.
 */
//--------------------------------------------------------
Tango::DbDatum NewPort8742CtrlClass::get_default_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : NewPort8742CtrlClass::set_default_property()
 *	Description : Set default property (class and device) for wizard.
 *                For each property, add to wizard property name and description.
 *                If default value has been set, add it to wizard property and
 *                store it in a DbDatum.
 */
//--------------------------------------------------------
void NewPort8742CtrlClass::set_default_property()
{
	string	prop_name;
	string	prop_desc;
	string	prop_def;
	vector<string>	vect_data;

	//	Set Default Class Properties

	//	Set Default device Properties
	prop_name = "HostName";
	prop_desc = "hostname or ip address of controller";
	prop_def  = """";
	vect_data.clear();
	vect_data.push_back("""");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "PortNumber";
	prop_desc = "tcp port number of controller";
	prop_def  = """";
	vect_data.clear();
	vect_data.push_back("""");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "ConnectType";
	prop_desc = "whenn connected via network, set to `net, when connected via usb, set to `usb`";
	prop_def  = """";
	vect_data.clear();
	vect_data.push_back("""");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "DeviceFile";
	prop_desc = "usb device file when connected via usb";
	prop_def  = """";
	vect_data.clear();
	vect_data.push_back("""");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
}

//--------------------------------------------------------
/**
 *	Method      : NewPort8742CtrlClass::write_class_property()
 *	Description : Set class description fields as property in database
 */
//--------------------------------------------------------
void NewPort8742CtrlClass::write_class_property()
{
	//	First time, check if database used
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	string	classname = get_name();
	string	header;
	string::size_type	start, end;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	string	str_title("NewPort8742Ctrl");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	vector<string>	str_desc;
	str_desc.push_back("Controller class for NewPort8742 piezo controller");
	description << str_desc;
	data.push_back(description);

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	vector<string> inheritance;
	inheritance.push_back("TANGO_BASE_CLASS");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	get_db_class()->put_property(data);
}

//===================================================================
//	Factory methods
//===================================================================

//--------------------------------------------------------
/**
 *	Method      : NewPort8742CtrlClass::device_factory()
 *	Description : Create the device object(s)
 *                and store them in the device list
 */
//--------------------------------------------------------
void NewPort8742CtrlClass::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{
	/*----- PROTECTED REGION ID(NewPort8742CtrlClass::device_factory_before) ENABLED START -----*/

	//	Add your own code

	/*----- PROTECTED REGION END -----*/	//	NewPort8742CtrlClass::device_factory_before

	//	Create devices and add it into the device list
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
		device_list.push_back(new NewPort8742Ctrl(this, (*devlist_ptr)[i]));
	}

	//	Manage dynamic attributes if any
	erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

	//	Export devices to the outside world
	for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
	{
		//	Add dynamic attributes if any
		NewPort8742Ctrl *dev = static_cast<NewPort8742Ctrl *>(device_list[device_list.size()-i]);
		dev->add_dynamic_attributes();

		//	Check before if database used.
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(dev);
		else
			export_device(dev, dev->get_name().c_str());
	}

	/*----- PROTECTED REGION ID(NewPort8742CtrlClass::device_factory_after) ENABLED START -----*/

	//	Add your own code

	/*----- PROTECTED REGION END -----*/	//	NewPort8742CtrlClass::device_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : NewPort8742CtrlClass::attribute_factory()
 *	Description : Create the attribute object(s)
 *                and store them in the attribute list
 */
//--------------------------------------------------------
void NewPort8742CtrlClass::attribute_factory(vector<Tango::Attr *> &att_list)
{
	/*----- PROTECTED REGION ID(NewPort8742CtrlClass::attribute_factory_before) ENABLED START -----*/

	//	Add your own code

	/*----- PROTECTED REGION END -----*/	//	NewPort8742CtrlClass::attribute_factory_before

	//	Create a list of static attributes
	create_static_attribute_list(get_class_attr()->get_attr_list());
	/*----- PROTECTED REGION ID(NewPort8742CtrlClass::attribute_factory_after) ENABLED START -----*/

	//	Add your own code

	/*----- PROTECTED REGION END -----*/	//	NewPort8742CtrlClass::attribute_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : NewPort8742CtrlClass::pipe_factory()
 *	Description : Create the pipe object(s)
 *                and store them in the pipe list
 */
//--------------------------------------------------------
void NewPort8742CtrlClass::pipe_factory()
{
	/*----- PROTECTED REGION ID(NewPort8742CtrlClass::pipe_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	NewPort8742CtrlClass::pipe_factory_before
	/*----- PROTECTED REGION ID(NewPort8742CtrlClass::pipe_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	NewPort8742CtrlClass::pipe_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : NewPort8742CtrlClass::command_factory()
 *	Description : Create the command object(s)
 *                and store them in the command list
 */
//--------------------------------------------------------
void NewPort8742CtrlClass::command_factory()
{
	/*----- PROTECTED REGION ID(NewPort8742CtrlClass::command_factory_before) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	NewPort8742CtrlClass::command_factory_before


	//	Command Write
	WriteClass	*pWriteCmd =
		new WriteClass("Write",
			Tango::DEV_STRING, Tango::DEV_VOID,
			"command to send",
			"",
			Tango::OPERATOR);
	command_list.push_back(pWriteCmd);

	//	Command WriteReadString
	WriteReadStringClass	*pWriteReadStringCmd =
		new WriteReadStringClass("WriteReadString",
			Tango::DEV_STRING, Tango::DEV_STRING,
			"command to send",
			"reply we got",
			Tango::OPERATOR);
	command_list.push_back(pWriteReadStringCmd);

	//	Command WriteReadLong
	WriteReadLongClass	*pWriteReadLongCmd =
		new WriteReadLongClass("WriteReadLong",
			Tango::DEV_STRING, Tango::DEV_LONG,
			"command to send",
			"reply we got",
			Tango::OPERATOR);
	command_list.push_back(pWriteReadLongCmd);

	//	Command Reset
	ResetClass	*pResetCmd =
		new ResetClass("Reset",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pResetCmd);

	/*----- PROTECTED REGION ID(NewPort8742CtrlClass::command_factory_after) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	NewPort8742CtrlClass::command_factory_after
}

//===================================================================
//	Dynamic attributes related methods
//===================================================================

//--------------------------------------------------------
/**
 * method : 		NewPort8742CtrlClass::create_static_attribute_list
 * description : 	Create the a list of static attributes
 *
 * @param	att_list	the ceated attribute list
 */
//--------------------------------------------------------
void NewPort8742CtrlClass::create_static_attribute_list(vector<Tango::Attr *> &att_list)
{
	for (unsigned long i=0 ; i<att_list.size() ; i++)
	{
		string att_name(att_list[i]->get_name());
		transform(att_name.begin(), att_name.end(), att_name.begin(), ::tolower);
		defaultAttList.push_back(att_name);
	}

	cout2 << defaultAttList.size() << " attributes in default list" << endl;

	/*----- PROTECTED REGION ID(NewPort8742CtrlClass::create_static_att_list) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	NewPort8742CtrlClass::create_static_att_list
}


//--------------------------------------------------------
/**
 * method : 		NewPort8742CtrlClass::erase_dynamic_attributes
 * description : 	delete the dynamic attributes if any.
 *
 * @param	devlist_ptr	the device list pointer
 * @param	list of all attributes
 */
//--------------------------------------------------------
void NewPort8742CtrlClass::erase_dynamic_attributes(const Tango::DevVarStringArray *devlist_ptr, vector<Tango::Attr *> &att_list)
{
	Tango::Util *tg = Tango::Util::instance();

	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		Tango::DeviceImpl *dev_impl = tg->get_device_by_name(((string)(*devlist_ptr)[i]).c_str());
		NewPort8742Ctrl *dev = static_cast<NewPort8742Ctrl *> (dev_impl);

		vector<Tango::Attribute *> &dev_att_list = dev->get_device_attr()->get_attribute_list();
		vector<Tango::Attribute *>::iterator ite_att;
		for (ite_att=dev_att_list.begin() ; ite_att != dev_att_list.end() ; ++ite_att)
		{
			string att_name((*ite_att)->get_name_lower());
			if ((att_name == "state") || (att_name == "status"))
				continue;
			vector<string>::iterator ite_str = find(defaultAttList.begin(), defaultAttList.end(), att_name);
			if (ite_str == defaultAttList.end())
			{
				cout2 << att_name << " is a UNWANTED dynamic attribute for device " << (*devlist_ptr)[i] << endl;
				Tango::Attribute &att = dev->get_device_attr()->get_attr_by_name(att_name.c_str());
				dev->remove_attribute(att_list[att.get_attr_idx()], true, false);
				--ite_att;
			}
		}
	}
	/*----- PROTECTED REGION ID(NewPort8742CtrlClass::erase_dynamic_attributes) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	NewPort8742CtrlClass::erase_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method      : NewPort8742CtrlClass::get_attr_object_by_name()
 *	Description : returns Tango::Attr * object found by name
 */
//--------------------------------------------------------
Tango::Attr *NewPort8742CtrlClass::get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname)
{
	vector<Tango::Attr *>::iterator it;
	for (it=att_list.begin() ; it<att_list.end() ; ++it)
		if ((*it)->get_name()==attname)
			return (*it);
	//	Attr does not exist
	return NULL;
}


/*----- PROTECTED REGION ID(NewPort8742CtrlClass::Additional Methods) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	NewPort8742CtrlClass::Additional Methods
} //	namespace
