/*----- PROTECTED REGION ID(TimingUnitClass.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        TimingUnitClass.cpp
//
// description : C++ source for the TimingUnitClass.
//               A singleton class derived from DeviceClass.
//               It implements the command and attribute list
//               and all properties and methods required
//               by the TimingUnit once per process.
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <TimingUnitClass.h>

/*----- PROTECTED REGION END -----*/	//	TimingUnitClass.cpp

//-------------------------------------------------------------------
/**
 *	Create TimingUnitClass singleton and
 *	return it in a C function for Python usage
 */
//-------------------------------------------------------------------
extern "C" {
#ifdef _TG_WINDOWS_

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_TimingUnit_class(const char *name) {
		return TimingUnit_ns::TimingUnitClass::init(name);
	}
}

namespace TimingUnit_ns
{
//===================================================================
//	Initialize pointer for singleton pattern
//===================================================================
TimingUnitClass *TimingUnitClass::_instance = NULL;

//--------------------------------------------------------
/**
 * method : 		TimingUnitClass::TimingUnitClass(string &s)
 * description : 	constructor for the TimingUnitClass
 *
 * @param s	The class name
 */
//--------------------------------------------------------
TimingUnitClass::TimingUnitClass(string &s):Tango::DeviceClass(s)
{
	cout2 << "Entering TimingUnitClass constructor" << endl;
	set_default_property();
	write_class_property();

	/*----- PROTECTED REGION ID(TimingUnitClass::constructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnitClass::constructor

	cout2 << "Leaving TimingUnitClass constructor" << endl;
}

//--------------------------------------------------------
/**
 * method : 		TimingUnitClass::~TimingUnitClass()
 * description : 	destructor for the TimingUnitClass
 */
//--------------------------------------------------------
TimingUnitClass::~TimingUnitClass()
{
	/*----- PROTECTED REGION ID(TimingUnitClass::destructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnitClass::destructor

	_instance = NULL;
}


//--------------------------------------------------------
/**
 * method : 		TimingUnitClass::init
 * description : 	Create the object if not already done.
 *                  Otherwise, just return a pointer to the object
 *
 * @param	name	The class name
 */
//--------------------------------------------------------
TimingUnitClass *TimingUnitClass::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new TimingUnitClass(s);
		}
		catch (bad_alloc &)
		{
			throw;
		}
	}
	return _instance;
}

//--------------------------------------------------------
/**
 * method : 		TimingUnitClass::instance
 * description : 	Check if object already created,
 *                  and return a pointer to the object
 */
//--------------------------------------------------------
TimingUnitClass *TimingUnitClass::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}



//===================================================================
//	Command execution method calls
//===================================================================

//===================================================================
//	Properties management
//===================================================================
//--------------------------------------------------------
/**
 *	Method      : TimingUnitClass::get_class_property()
 *	Description : Get the class property for specified name.
 */
//--------------------------------------------------------
Tango::DbDatum TimingUnitClass::get_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, returns  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : TimingUnitClass::get_default_device_property()
 *	Description : Return the default value for device property.
 */
//--------------------------------------------------------
Tango::DbDatum TimingUnitClass::get_default_device_property(string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : TimingUnitClass::get_default_class_property()
 *	Description : Return the default value for class property.
 */
//--------------------------------------------------------
Tango::DbDatum TimingUnitClass::get_default_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : TimingUnitClass::set_default_property()
 *	Description : Set default property (class and device) for wizard.
 *                For each property, add to wizard property name and description.
 *                If default value has been set, add it to wizard property and
 *                store it in a DbDatum.
 */
//--------------------------------------------------------
void TimingUnitClass::set_default_property()
{
	string	prop_name;
	string	prop_desc;
	string	prop_def;
	vector<string>	vect_data;

	//	Set Default Class Properties

	//	Set Default device Properties
}

//--------------------------------------------------------
/**
 *	Method      : TimingUnitClass::write_class_property()
 *	Description : Set class description fields as property in database
 */
//--------------------------------------------------------
void TimingUnitClass::write_class_property()
{
	//	First time, check if database used
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	string	classname = get_name();
	string	header;
	string::size_type	start, end;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	string	str_title("");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	vector<string>	str_desc;
	str_desc.push_back("");
	description << str_desc;
	data.push_back(description);

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	vector<string> inheritance;
	inheritance.push_back("TANGO_BASE_CLASS");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	get_db_class()->put_property(data);
}

//===================================================================
//	Factory methods
//===================================================================

//--------------------------------------------------------
/**
 *	Method      : TimingUnitClass::device_factory()
 *	Description : Create the device object(s)
 *                and store them in the device list
 */
//--------------------------------------------------------
void TimingUnitClass::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{
	/*----- PROTECTED REGION ID(TimingUnitClass::device_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnitClass::device_factory_before

	//	Create devices and add it into the device list
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
		device_list.push_back(new TimingUnit(this, (*devlist_ptr)[i]));
	}

	//	Manage dynamic attributes if any
	erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

	//	Export devices to the outside world
	for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
	{
		//	Add dynamic attributes if any
		TimingUnit *dev = static_cast<TimingUnit *>(device_list[device_list.size()-i]);
		dev->add_dynamic_attributes();

		//	Check before if database used.
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(dev);
		else
			export_device(dev, dev->get_name().c_str());
	}

	/*----- PROTECTED REGION ID(TimingUnitClass::device_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnitClass::device_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : TimingUnitClass::attribute_factory()
 *	Description : Create the attribute object(s)
 *                and store them in the attribute list
 */
//--------------------------------------------------------
void TimingUnitClass::attribute_factory(vector<Tango::Attr *> &att_list)
{
	/*----- PROTECTED REGION ID(TimingUnitClass::attribute_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnitClass::attribute_factory_before
	//	Attribute : DelayLine0
	DelayLine0Attrib	*delayline0 = new DelayLine0Attrib();
	Tango::UserDefaultAttrProp	delayline0_prop;
	//	description	not set for DelayLine0
	delayline0_prop.set_label("Delay Line 0");
	delayline0_prop.set_unit("Milliseconds");
	delayline0_prop.set_standard_unit("Milliseconds");
	delayline0_prop.set_display_unit("ms");
	delayline0_prop.set_format("%3.2f");
	//	max_value	not set for DelayLine0
	//	min_value	not set for DelayLine0
	//	max_alarm	not set for DelayLine0
	//	min_alarm	not set for DelayLine0
	//	max_warning	not set for DelayLine0
	//	min_warning	not set for DelayLine0
	//	delta_t	not set for DelayLine0
	//	delta_val	not set for DelayLine0
	
	delayline0->set_default_properties(delayline0_prop);
	//	Not Polled
	delayline0->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(delayline0);

	//	Attribute : DelayLine1
	DelayLine1Attrib	*delayline1 = new DelayLine1Attrib();
	Tango::UserDefaultAttrProp	delayline1_prop;
	//	description	not set for DelayLine1
	delayline1_prop.set_label("Delay Line 1");
	delayline1_prop.set_unit("Milliseconds");
	delayline1_prop.set_standard_unit("Milliseconds");
	delayline1_prop.set_display_unit("ms");
	delayline1_prop.set_format("%3.2f");
	//	max_value	not set for DelayLine1
	//	min_value	not set for DelayLine1
	//	max_alarm	not set for DelayLine1
	//	min_alarm	not set for DelayLine1
	//	max_warning	not set for DelayLine1
	//	min_warning	not set for DelayLine1
	//	delta_t	not set for DelayLine1
	//	delta_val	not set for DelayLine1
	
	delayline1->set_default_properties(delayline1_prop);
	//	Not Polled
	delayline1->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(delayline1);

	//	Attribute : DelayLine2
	DelayLine2Attrib	*delayline2 = new DelayLine2Attrib();
	Tango::UserDefaultAttrProp	delayline2_prop;
	//	description	not set for DelayLine2
	delayline2_prop.set_label("Delay Line 2");
	delayline2_prop.set_unit("Milliseconds");
	delayline2_prop.set_standard_unit("Milliseconds");
	delayline2_prop.set_display_unit("ms");
	delayline2_prop.set_format("%3.2f");
	//	max_value	not set for DelayLine2
	//	min_value	not set for DelayLine2
	//	max_alarm	not set for DelayLine2
	//	min_alarm	not set for DelayLine2
	//	max_warning	not set for DelayLine2
	//	min_warning	not set for DelayLine2
	//	delta_t	not set for DelayLine2
	//	delta_val	not set for DelayLine2
	
	delayline2->set_default_properties(delayline2_prop);
	//	Not Polled
	delayline2->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(delayline2);

	//	Attribute : DelayLine3
	DelayLine3Attrib	*delayline3 = new DelayLine3Attrib();
	Tango::UserDefaultAttrProp	delayline3_prop;
	//	description	not set for DelayLine3
	delayline3_prop.set_label("Delay Line 3");
	delayline3_prop.set_unit("Milliseconds");
	delayline3_prop.set_standard_unit("Milliseconds");
	delayline3_prop.set_display_unit("ms");
	delayline3_prop.set_format("%3.2f");
	//	max_value	not set for DelayLine3
	//	min_value	not set for DelayLine3
	//	max_alarm	not set for DelayLine3
	//	min_alarm	not set for DelayLine3
	//	max_warning	not set for DelayLine3
	//	min_warning	not set for DelayLine3
	//	delta_t	not set for DelayLine3
	//	delta_val	not set for DelayLine3
	
	delayline3->set_default_properties(delayline3_prop);
	//	Not Polled
	delayline3->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(delayline3);

	//	Attribute : DelayLine4
	DelayLine4Attrib	*delayline4 = new DelayLine4Attrib();
	Tango::UserDefaultAttrProp	delayline4_prop;
	//	description	not set for DelayLine4
	delayline4_prop.set_label("Delay Line 4");
	delayline4_prop.set_unit("Milliseconds");
	delayline4_prop.set_standard_unit("Milliseconds");
	delayline4_prop.set_display_unit("ms");
	delayline4_prop.set_format("%3.2f");
	//	max_value	not set for DelayLine4
	//	min_value	not set for DelayLine4
	//	max_alarm	not set for DelayLine4
	//	min_alarm	not set for DelayLine4
	//	max_warning	not set for DelayLine4
	//	min_warning	not set for DelayLine4
	//	delta_t	not set for DelayLine4
	//	delta_val	not set for DelayLine4
	
	delayline4->set_default_properties(delayline4_prop);
	//	Not Polled
	delayline4->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(delayline4);

	//	Attribute : DelayLine5
	DelayLine5Attrib	*delayline5 = new DelayLine5Attrib();
	Tango::UserDefaultAttrProp	delayline5_prop;
	//	description	not set for DelayLine5
	delayline5_prop.set_label("Delay Line 5");
	delayline5_prop.set_unit("Milliseconds");
	delayline5_prop.set_standard_unit("Milliseconds");
	delayline5_prop.set_display_unit("ms");
	delayline5_prop.set_format("%3.2f");
	//	max_value	not set for DelayLine5
	//	min_value	not set for DelayLine5
	//	max_alarm	not set for DelayLine5
	//	min_alarm	not set for DelayLine5
	//	max_warning	not set for DelayLine5
	//	min_warning	not set for DelayLine5
	//	delta_t	not set for DelayLine5
	//	delta_val	not set for DelayLine5
	
	delayline5->set_default_properties(delayline5_prop);
	//	Not Polled
	delayline5->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(delayline5);

	//	Attribute : Output_B0
	Output_B0Attrib	*output_b0 = new Output_B0Attrib();
	Tango::UserDefaultAttrProp	output_b0_prop;
	//	description	not set for Output_B0
	output_b0_prop.set_label("Output B0");
	//	unit	not set for Output_B0
	//	standard_unit	not set for Output_B0
	//	display_unit	not set for Output_B0
	//	format	not set for Output_B0
	//	max_value	not set for Output_B0
	//	min_value	not set for Output_B0
	//	max_alarm	not set for Output_B0
	//	min_alarm	not set for Output_B0
	//	max_warning	not set for Output_B0
	//	min_warning	not set for Output_B0
	//	delta_t	not set for Output_B0
	//	delta_val	not set for Output_B0
	
	{
		vector<string> labels;
		labels.push_back("DelayLine0");
		labels.push_back("DelayLine1");
		labels.push_back("DelayLine2");
		labels.push_back("DelayLine3");
		labels.push_back("DelayLine4");
		labels.push_back("DelayLine5");
		output_b0_prop.set_enum_labels(labels);
	}
	output_b0->set_default_properties(output_b0_prop);
	//	Not Polled
	output_b0->set_disp_level(Tango::OPERATOR);
	output_b0->set_memorized();
	output_b0->set_memorized_init(true);
	att_list.push_back(output_b0);

	//	Attribute : Output_B1
	Output_B1Attrib	*output_b1 = new Output_B1Attrib();
	Tango::UserDefaultAttrProp	output_b1_prop;
	//	description	not set for Output_B1
	output_b1_prop.set_label("Output B1");
	//	unit	not set for Output_B1
	//	standard_unit	not set for Output_B1
	//	display_unit	not set for Output_B1
	//	format	not set for Output_B1
	//	max_value	not set for Output_B1
	//	min_value	not set for Output_B1
	//	max_alarm	not set for Output_B1
	//	min_alarm	not set for Output_B1
	//	max_warning	not set for Output_B1
	//	min_warning	not set for Output_B1
	//	delta_t	not set for Output_B1
	//	delta_val	not set for Output_B1
	
	{
		vector<string> labels;
		labels.push_back("DelayLine0");
		labels.push_back("DelayLine1");
		labels.push_back("DelayLine2");
		labels.push_back("DelayLine3");
		labels.push_back("DelayLine4");
		labels.push_back("DelayLine5");
		output_b1_prop.set_enum_labels(labels);
	}
	output_b1->set_default_properties(output_b1_prop);
	//	Not Polled
	output_b1->set_disp_level(Tango::OPERATOR);
	output_b1->set_memorized();
	output_b1->set_memorized_init(true);
	att_list.push_back(output_b1);

	//	Attribute : Output_B2
	Output_B2Attrib	*output_b2 = new Output_B2Attrib();
	Tango::UserDefaultAttrProp	output_b2_prop;
	//	description	not set for Output_B2
	output_b2_prop.set_label("Output B2");
	//	unit	not set for Output_B2
	//	standard_unit	not set for Output_B2
	//	display_unit	not set for Output_B2
	//	format	not set for Output_B2
	//	max_value	not set for Output_B2
	//	min_value	not set for Output_B2
	//	max_alarm	not set for Output_B2
	//	min_alarm	not set for Output_B2
	//	max_warning	not set for Output_B2
	//	min_warning	not set for Output_B2
	//	delta_t	not set for Output_B2
	//	delta_val	not set for Output_B2
	
	{
		vector<string> labels;
		labels.push_back("DelayLine0");
		labels.push_back("DelayLine1");
		labels.push_back("DelayLine2");
		labels.push_back("DelayLine3");
		labels.push_back("DelayLine4");
		labels.push_back("DelayLine5");
		output_b2_prop.set_enum_labels(labels);
	}
	output_b2->set_default_properties(output_b2_prop);
	//	Not Polled
	output_b2->set_disp_level(Tango::OPERATOR);
	output_b2->set_memorized();
	output_b2->set_memorized_init(true);
	att_list.push_back(output_b2);

	//	Attribute : Output_B3
	Output_B3Attrib	*output_b3 = new Output_B3Attrib();
	Tango::UserDefaultAttrProp	output_b3_prop;
	//	description	not set for Output_B3
	output_b3_prop.set_label("Output B3");
	//	unit	not set for Output_B3
	//	standard_unit	not set for Output_B3
	//	display_unit	not set for Output_B3
	//	format	not set for Output_B3
	//	max_value	not set for Output_B3
	//	min_value	not set for Output_B3
	//	max_alarm	not set for Output_B3
	//	min_alarm	not set for Output_B3
	//	max_warning	not set for Output_B3
	//	min_warning	not set for Output_B3
	//	delta_t	not set for Output_B3
	//	delta_val	not set for Output_B3
	
	{
		vector<string> labels;
		labels.push_back("DelayLine0");
		labels.push_back("DelayLine1");
		labels.push_back("DelayLine2");
		labels.push_back("DelayLine3");
		labels.push_back("DelayLine4");
		labels.push_back("DelayLine5");
		output_b3_prop.set_enum_labels(labels);
	}
	output_b3->set_default_properties(output_b3_prop);
	//	Not Polled
	output_b3->set_disp_level(Tango::OPERATOR);
	output_b3->set_memorized();
	output_b3->set_memorized_init(true);
	att_list.push_back(output_b3);

	//	Attribute : Output_B4
	Output_B4Attrib	*output_b4 = new Output_B4Attrib();
	Tango::UserDefaultAttrProp	output_b4_prop;
	//	description	not set for Output_B4
	output_b4_prop.set_label("Output B4");
	//	unit	not set for Output_B4
	//	standard_unit	not set for Output_B4
	//	display_unit	not set for Output_B4
	//	format	not set for Output_B4
	//	max_value	not set for Output_B4
	//	min_value	not set for Output_B4
	//	max_alarm	not set for Output_B4
	//	min_alarm	not set for Output_B4
	//	max_warning	not set for Output_B4
	//	min_warning	not set for Output_B4
	//	delta_t	not set for Output_B4
	//	delta_val	not set for Output_B4
	
	{
		vector<string> labels;
		labels.push_back("DelayLine0");
		labels.push_back("DelayLine1");
		labels.push_back("DelayLine2");
		labels.push_back("DelayLine3");
		labels.push_back("DelayLine4");
		labels.push_back("DelayLine5");
		output_b4_prop.set_enum_labels(labels);
	}
	output_b4->set_default_properties(output_b4_prop);
	//	Not Polled
	output_b4->set_disp_level(Tango::OPERATOR);
	output_b4->set_memorized();
	output_b4->set_memorized_init(true);
	att_list.push_back(output_b4);

	//	Attribute : Output_B5
	Output_B5Attrib	*output_b5 = new Output_B5Attrib();
	Tango::UserDefaultAttrProp	output_b5_prop;
	//	description	not set for Output_B5
	output_b5_prop.set_label("Output B5");
	//	unit	not set for Output_B5
	//	standard_unit	not set for Output_B5
	//	display_unit	not set for Output_B5
	//	format	not set for Output_B5
	//	max_value	not set for Output_B5
	//	min_value	not set for Output_B5
	//	max_alarm	not set for Output_B5
	//	min_alarm	not set for Output_B5
	//	max_warning	not set for Output_B5
	//	min_warning	not set for Output_B5
	//	delta_t	not set for Output_B5
	//	delta_val	not set for Output_B5
	
	{
		vector<string> labels;
		labels.push_back("DelayLine0");
		labels.push_back("DelayLine1");
		labels.push_back("DelayLine2");
		labels.push_back("DelayLine3");
		labels.push_back("DelayLine4");
		labels.push_back("DelayLine5");
		output_b5_prop.set_enum_labels(labels);
	}
	output_b5->set_default_properties(output_b5_prop);
	//	Not Polled
	output_b5->set_disp_level(Tango::OPERATOR);
	output_b5->set_memorized();
	output_b5->set_memorized_init(true);
	att_list.push_back(output_b5);

	//	Attribute : Output_B6
	Output_B6Attrib	*output_b6 = new Output_B6Attrib();
	Tango::UserDefaultAttrProp	output_b6_prop;
	//	description	not set for Output_B6
	output_b6_prop.set_label("Output B6");
	//	unit	not set for Output_B6
	//	standard_unit	not set for Output_B6
	//	display_unit	not set for Output_B6
	//	format	not set for Output_B6
	//	max_value	not set for Output_B6
	//	min_value	not set for Output_B6
	//	max_alarm	not set for Output_B6
	//	min_alarm	not set for Output_B6
	//	max_warning	not set for Output_B6
	//	min_warning	not set for Output_B6
	//	delta_t	not set for Output_B6
	//	delta_val	not set for Output_B6
	
	{
		vector<string> labels;
		labels.push_back("DelayLine0");
		labels.push_back("DelayLine1");
		labels.push_back("DelayLine2");
		labels.push_back("DelayLine3");
		labels.push_back("DelayLine4");
		labels.push_back("DelayLine5");
		output_b6_prop.set_enum_labels(labels);
	}
	output_b6->set_default_properties(output_b6_prop);
	//	Not Polled
	output_b6->set_disp_level(Tango::OPERATOR);
	output_b6->set_memorized();
	output_b6->set_memorized_init(true);
	att_list.push_back(output_b6);

	//	Attribute : Output_B7
	Output_B7Attrib	*output_b7 = new Output_B7Attrib();
	Tango::UserDefaultAttrProp	output_b7_prop;
	//	description	not set for Output_B7
	output_b7_prop.set_label("Output B7");
	//	unit	not set for Output_B7
	//	standard_unit	not set for Output_B7
	//	display_unit	not set for Output_B7
	//	format	not set for Output_B7
	//	max_value	not set for Output_B7
	//	min_value	not set for Output_B7
	//	max_alarm	not set for Output_B7
	//	min_alarm	not set for Output_B7
	//	max_warning	not set for Output_B7
	//	min_warning	not set for Output_B7
	//	delta_t	not set for Output_B7
	//	delta_val	not set for Output_B7
	
	{
		vector<string> labels;
		labels.push_back("DelayLine0");
		labels.push_back("DelayLine1");
		labels.push_back("DelayLine2");
		labels.push_back("DelayLine3");
		labels.push_back("DelayLine4");
		labels.push_back("DelayLine5");
		output_b7_prop.set_enum_labels(labels);
	}
	output_b7->set_default_properties(output_b7_prop);
	//	Not Polled
	output_b7->set_disp_level(Tango::OPERATOR);
	output_b7->set_memorized();
	output_b7->set_memorized_init(true);
	att_list.push_back(output_b7);

	//	Attribute : Output_D0
	Output_D0Attrib	*output_d0 = new Output_D0Attrib();
	Tango::UserDefaultAttrProp	output_d0_prop;
	//	description	not set for Output_D0
	output_d0_prop.set_label("Output D0");
	//	unit	not set for Output_D0
	//	standard_unit	not set for Output_D0
	//	display_unit	not set for Output_D0
	//	format	not set for Output_D0
	//	max_value	not set for Output_D0
	//	min_value	not set for Output_D0
	//	max_alarm	not set for Output_D0
	//	min_alarm	not set for Output_D0
	//	max_warning	not set for Output_D0
	//	min_warning	not set for Output_D0
	//	delta_t	not set for Output_D0
	//	delta_val	not set for Output_D0
	
	{
		vector<string> labels;
		labels.push_back("DelayLine0");
		labels.push_back("DelayLine1");
		labels.push_back("DelayLine2");
		labels.push_back("DelayLine3");
		labels.push_back("DelayLine4");
		labels.push_back("DelayLine5");
		output_d0_prop.set_enum_labels(labels);
	}
	output_d0->set_default_properties(output_d0_prop);
	//	Not Polled
	output_d0->set_disp_level(Tango::OPERATOR);
	output_d0->set_memorized();
	output_d0->set_memorized_init(true);
	att_list.push_back(output_d0);

	//	Attribute : Output_D1
	Output_D1Attrib	*output_d1 = new Output_D1Attrib();
	Tango::UserDefaultAttrProp	output_d1_prop;
	//	description	not set for Output_D1
	output_d1_prop.set_label("Output D1");
	//	unit	not set for Output_D1
	//	standard_unit	not set for Output_D1
	//	display_unit	not set for Output_D1
	//	format	not set for Output_D1
	//	max_value	not set for Output_D1
	//	min_value	not set for Output_D1
	//	max_alarm	not set for Output_D1
	//	min_alarm	not set for Output_D1
	//	max_warning	not set for Output_D1
	//	min_warning	not set for Output_D1
	//	delta_t	not set for Output_D1
	//	delta_val	not set for Output_D1
	
	{
		vector<string> labels;
		labels.push_back("DelayLine0");
		labels.push_back("DelayLine1");
		labels.push_back("DelayLine2");
		labels.push_back("DelayLine3");
		labels.push_back("DelayLine4");
		labels.push_back("DelayLine5");
		output_d1_prop.set_enum_labels(labels);
	}
	output_d1->set_default_properties(output_d1_prop);
	//	Not Polled
	output_d1->set_disp_level(Tango::OPERATOR);
	output_d1->set_memorized();
	output_d1->set_memorized_init(true);
	att_list.push_back(output_d1);

	//	Attribute : Output_D2
	Output_D2Attrib	*output_d2 = new Output_D2Attrib();
	Tango::UserDefaultAttrProp	output_d2_prop;
	//	description	not set for Output_D2
	output_d2_prop.set_label("Output D2");
	//	unit	not set for Output_D2
	//	standard_unit	not set for Output_D2
	//	display_unit	not set for Output_D2
	//	format	not set for Output_D2
	//	max_value	not set for Output_D2
	//	min_value	not set for Output_D2
	//	max_alarm	not set for Output_D2
	//	min_alarm	not set for Output_D2
	//	max_warning	not set for Output_D2
	//	min_warning	not set for Output_D2
	//	delta_t	not set for Output_D2
	//	delta_val	not set for Output_D2
	
	{
		vector<string> labels;
		labels.push_back("DelayLine0");
		labels.push_back("DelayLine1");
		labels.push_back("DelayLine2");
		labels.push_back("DelayLine3");
		labels.push_back("DelayLine4");
		labels.push_back("DelayLine5");
		output_d2_prop.set_enum_labels(labels);
	}
	output_d2->set_default_properties(output_d2_prop);
	//	Not Polled
	output_d2->set_disp_level(Tango::OPERATOR);
	output_d2->set_memorized();
	output_d2->set_memorized_init(true);
	att_list.push_back(output_d2);

	//	Attribute : Output_D3
	Output_D3Attrib	*output_d3 = new Output_D3Attrib();
	Tango::UserDefaultAttrProp	output_d3_prop;
	//	description	not set for Output_D3
	output_d3_prop.set_label("Output D3");
	//	unit	not set for Output_D3
	//	standard_unit	not set for Output_D3
	//	display_unit	not set for Output_D3
	//	format	not set for Output_D3
	//	max_value	not set for Output_D3
	//	min_value	not set for Output_D3
	//	max_alarm	not set for Output_D3
	//	min_alarm	not set for Output_D3
	//	max_warning	not set for Output_D3
	//	min_warning	not set for Output_D3
	//	delta_t	not set for Output_D3
	//	delta_val	not set for Output_D3
	
	{
		vector<string> labels;
		labels.push_back("DelayLine0");
		labels.push_back("DelayLine1");
		labels.push_back("DelayLine2");
		labels.push_back("DelayLine3");
		labels.push_back("DelayLine4");
		labels.push_back("DelayLine5");
		output_d3_prop.set_enum_labels(labels);
	}
	output_d3->set_default_properties(output_d3_prop);
	//	Not Polled
	output_d3->set_disp_level(Tango::OPERATOR);
	output_d3->set_memorized();
	output_d3->set_memorized_init(true);
	att_list.push_back(output_d3);


	//	Create a list of static attributes
	create_static_attribute_list(get_class_attr()->get_attr_list());
	/*----- PROTECTED REGION ID(TimingUnitClass::attribute_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnitClass::attribute_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : TimingUnitClass::pipe_factory()
 *	Description : Create the pipe object(s)
 *                and store them in the pipe list
 */
//--------------------------------------------------------
void TimingUnitClass::pipe_factory()
{
	/*----- PROTECTED REGION ID(TimingUnitClass::pipe_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnitClass::pipe_factory_before
	/*----- PROTECTED REGION ID(TimingUnitClass::pipe_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnitClass::pipe_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : TimingUnitClass::command_factory()
 *	Description : Create the command object(s)
 *                and store them in the command list
 */
//--------------------------------------------------------
void TimingUnitClass::command_factory()
{
	/*----- PROTECTED REGION ID(TimingUnitClass::command_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnitClass::command_factory_before


	/*----- PROTECTED REGION ID(TimingUnitClass::command_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnitClass::command_factory_after
}

//===================================================================
//	Dynamic attributes related methods
//===================================================================

//--------------------------------------------------------
/**
 * method : 		TimingUnitClass::create_static_attribute_list
 * description : 	Create the a list of static attributes
 *
 * @param	att_list	the ceated attribute list
 */
//--------------------------------------------------------
void TimingUnitClass::create_static_attribute_list(vector<Tango::Attr *> &att_list)
{
	for (unsigned long i=0 ; i<att_list.size() ; i++)
	{
		string att_name(att_list[i]->get_name());
		transform(att_name.begin(), att_name.end(), att_name.begin(), ::tolower);
		defaultAttList.push_back(att_name);
	}

	cout2 << defaultAttList.size() << " attributes in default list" << endl;

	/*----- PROTECTED REGION ID(TimingUnitClass::create_static_att_list) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnitClass::create_static_att_list
}


//--------------------------------------------------------
/**
 * method : 		TimingUnitClass::erase_dynamic_attributes
 * description : 	delete the dynamic attributes if any.
 *
 * @param	devlist_ptr	the device list pointer
 * @param	list of all attributes
 */
//--------------------------------------------------------
void TimingUnitClass::erase_dynamic_attributes(const Tango::DevVarStringArray *devlist_ptr, vector<Tango::Attr *> &att_list)
{
	Tango::Util *tg = Tango::Util::instance();

	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		Tango::DeviceImpl *dev_impl = tg->get_device_by_name(((string)(*devlist_ptr)[i]).c_str());
		TimingUnit *dev = static_cast<TimingUnit *> (dev_impl);

		vector<Tango::Attribute *> &dev_att_list = dev->get_device_attr()->get_attribute_list();
		vector<Tango::Attribute *>::iterator ite_att;
		for (ite_att=dev_att_list.begin() ; ite_att != dev_att_list.end() ; ++ite_att)
		{
			string att_name((*ite_att)->get_name_lower());
			if ((att_name == "state") || (att_name == "status"))
				continue;
			vector<string>::iterator ite_str = find(defaultAttList.begin(), defaultAttList.end(), att_name);
			if (ite_str == defaultAttList.end())
			{
				cout2 << att_name << " is a UNWANTED dynamic attribute for device " << (*devlist_ptr)[i] << endl;
				Tango::Attribute &att = dev->get_device_attr()->get_attr_by_name(att_name.c_str());
				dev->remove_attribute(att_list[att.get_attr_idx()], true, false);
				--ite_att;
			}
		}
	}
	/*----- PROTECTED REGION ID(TimingUnitClass::erase_dynamic_attributes) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnitClass::erase_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method      : TimingUnitClass::get_attr_object_by_name()
 *	Description : returns Tango::Attr * object found by name
 */
//--------------------------------------------------------
Tango::Attr *TimingUnitClass::get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname)
{
	vector<Tango::Attr *>::iterator it;
	for (it=att_list.begin() ; it<att_list.end() ; ++it)
		if ((*it)->get_name()==attname)
			return (*it);
	//	Attr does not exist
	return NULL;
}


/*----- PROTECTED REGION ID(TimingUnitClass::Additional Methods) ENABLED START -----*/

/*----- PROTECTED REGION END -----*/	//	TimingUnitClass::Additional Methods
} //	namespace
