/*----- PROTECTED REGION ID(TimingUnit.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        TimingUnit.cpp
//
// description : C++ source for the TimingUnit class and its commands.
//               The class is derived from Device. It represents the
//               CORBA servant object which will be accessed from the
//               network. All commands which can be executed on the
//               TimingUnit are implemented in this file.
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <TimingUnit.h>
#include <TimingUnitClass.h>

/*----- PROTECTED REGION END -----*/	//	TimingUnit.cpp

/**
 *  TimingUnit class description:
 *    
 */

//================================================================
//  The following table gives the correspondence
//  between command and method names.
//
//  Command name  |  Method name
//================================================================
//  State         |  Inherited (no method)
//  Status        |  Inherited (no method)
//================================================================

//================================================================
//  Attributes managed are:
//================================================================
//  DelayLine0  |  Tango::DevUShort	Scalar
//  DelayLine1  |  Tango::DevUShort	Scalar
//  DelayLine2  |  Tango::DevUShort	Scalar
//  DelayLine3  |  Tango::DevUShort	Scalar
//  DelayLine4  |  Tango::DevUShort	Scalar
//  DelayLine5  |  Tango::DevUShort	Scalar
//  Output_B0   |  Tango::DevEnum	Scalar
//  Output_B1   |  Tango::DevEnum	Scalar
//  Output_B2   |  Tango::DevEnum	Scalar
//  Output_B3   |  Tango::DevEnum	Scalar
//  Output_B4   |  Tango::DevEnum	Scalar
//  Output_B5   |  Tango::DevEnum	Scalar
//  Output_B6   |  Tango::DevEnum	Scalar
//  Output_B7   |  Tango::DevEnum	Scalar
//  Output_D0   |  Tango::DevEnum	Scalar
//  Output_D1   |  Tango::DevEnum	Scalar
//  Output_D2   |  Tango::DevEnum	Scalar
//  Output_D3   |  Tango::DevEnum	Scalar
//================================================================

namespace TimingUnit_ns
{
/*----- PROTECTED REGION ID(TimingUnit::namespace_starting) ENABLED START -----*/

//	static initializations

/*----- PROTECTED REGION END -----*/	//	TimingUnit::namespace_starting

//--------------------------------------------------------
/**
 *	Method      : TimingUnit::TimingUnit()
 *	Description : Constructors for a Tango device
 *                implementing the classTimingUnit
 */
//--------------------------------------------------------
TimingUnit::TimingUnit(Tango::DeviceClass *cl, string &s)
 : TANGO_BASE_CLASS(cl, s.c_str())
{
	/*----- PROTECTED REGION ID(TimingUnit::constructor_1) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::constructor_1
}
//--------------------------------------------------------
TimingUnit::TimingUnit(Tango::DeviceClass *cl, const char *s)
 : TANGO_BASE_CLASS(cl, s)
{
	/*----- PROTECTED REGION ID(TimingUnit::constructor_2) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::constructor_2
}
//--------------------------------------------------------
TimingUnit::TimingUnit(Tango::DeviceClass *cl, const char *s, const char *d)
 : TANGO_BASE_CLASS(cl, s, d)
{
	/*----- PROTECTED REGION ID(TimingUnit::constructor_3) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::constructor_3
}

//--------------------------------------------------------
/**
 *	Method      : TimingUnit::delete_device()
 *	Description : will be called at device destruction or at init command
 */
//--------------------------------------------------------
void TimingUnit::delete_device()
{
	DEBUG_STREAM << "TimingUnit::delete_device() " << device_name << endl;
	/*----- PROTECTED REGION ID(TimingUnit::delete_device) ENABLED START -----*/
	
	//	Delete device allocated objects
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::delete_device
	delete[] attr_DelayLine0_read;
	delete[] attr_DelayLine1_read;
	delete[] attr_DelayLine2_read;
	delete[] attr_DelayLine3_read;
	delete[] attr_DelayLine4_read;
	delete[] attr_DelayLine5_read;
	delete[] attr_Output_B0_read;
	delete[] attr_Output_B1_read;
	delete[] attr_Output_B2_read;
	delete[] attr_Output_B3_read;
	delete[] attr_Output_B4_read;
	delete[] attr_Output_B5_read;
	delete[] attr_Output_B6_read;
	delete[] attr_Output_B7_read;
	delete[] attr_Output_D0_read;
	delete[] attr_Output_D1_read;
	delete[] attr_Output_D2_read;
	delete[] attr_Output_D3_read;
}

//--------------------------------------------------------
/**
 *	Method      : TimingUnit::init_device()
 *	Description : will be called at device initialization.
 */
//--------------------------------------------------------
void TimingUnit::init_device()
{
	DEBUG_STREAM << "TimingUnit::init_device() create device " << device_name << endl;
	/*----- PROTECTED REGION ID(TimingUnit::init_device_before) ENABLED START -----*/
	
	//	Initialization before get_device_property() call
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::init_device_before
	
	//	No device property to be read from database
	
	attr_DelayLine0_read = new Tango::DevUShort[1];
	attr_DelayLine1_read = new Tango::DevUShort[1];
	attr_DelayLine2_read = new Tango::DevUShort[1];
	attr_DelayLine3_read = new Tango::DevUShort[1];
	attr_DelayLine4_read = new Tango::DevUShort[1];
	attr_DelayLine5_read = new Tango::DevUShort[1];
	attr_Output_B0_read = new Output_B0Enum[1];
	attr_Output_B1_read = new Output_B1Enum[1];
	attr_Output_B2_read = new Output_B2Enum[1];
	attr_Output_B3_read = new Output_B3Enum[1];
	attr_Output_B4_read = new Output_B4Enum[1];
	attr_Output_B5_read = new Output_B5Enum[1];
	attr_Output_B6_read = new Output_B6Enum[1];
	attr_Output_B7_read = new Output_B7Enum[1];
	attr_Output_D0_read = new Output_D0Enum[1];
	attr_Output_D1_read = new Output_D1Enum[1];
	attr_Output_D2_read = new Output_D2Enum[1];
	attr_Output_D3_read = new Output_D3Enum[1];
	/*----- PROTECTED REGION ID(TimingUnit::init_device) ENABLED START -----*/
	
	//	Initialize device
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::init_device
}


//--------------------------------------------------------
/**
 *	Method      : TimingUnit::always_executed_hook()
 *	Description : method always executed before any command is executed
 */
//--------------------------------------------------------
void TimingUnit::always_executed_hook()
{
	DEBUG_STREAM << "TimingUnit::always_executed_hook()  " << device_name << endl;
	/*----- PROTECTED REGION ID(TimingUnit::always_executed_hook) ENABLED START -----*/
	
	//	code always executed before all requests
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::always_executed_hook
}

//--------------------------------------------------------
/**
 *	Method      : TimingUnit::read_attr_hardware()
 *	Description : Hardware acquisition for attributes
 */
//--------------------------------------------------------
void TimingUnit::read_attr_hardware(TANGO_UNUSED(vector<long> &attr_list))
{
	DEBUG_STREAM << "TimingUnit::read_attr_hardware(vector<long> &attr_list) entering... " << endl;
	/*----- PROTECTED REGION ID(TimingUnit::read_attr_hardware) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::read_attr_hardware
}
//--------------------------------------------------------
/**
 *	Method      : TimingUnit::write_attr_hardware()
 *	Description : Hardware writing for attributes
 */
//--------------------------------------------------------
void TimingUnit::write_attr_hardware(TANGO_UNUSED(vector<long> &attr_list))
{
	DEBUG_STREAM << "TimingUnit::write_attr_hardware(vector<long> &attr_list) entering... " << endl;
	/*----- PROTECTED REGION ID(TimingUnit::write_attr_hardware) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::write_attr_hardware
}

//--------------------------------------------------------
/**
 *	Read attribute DelayLine0 related method
 *	Description: 
 *
 *	Data type:	Tango::DevUShort
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TimingUnit::read_DelayLine0(Tango::Attribute &attr)
{
	DEBUG_STREAM << "TimingUnit::read_DelayLine0(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(TimingUnit::read_DelayLine0) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_DelayLine0_read);
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::read_DelayLine0
}
//--------------------------------------------------------
/**
 *	Write attribute DelayLine0 related method
 *	Description: 
 *
 *	Data type:	Tango::DevUShort
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TimingUnit::write_DelayLine0(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "TimingUnit::write_DelayLine0(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevUShort	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(TimingUnit::write_DelayLine0) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::write_DelayLine0
}
//--------------------------------------------------------
/**
 *	Read attribute DelayLine1 related method
 *	Description: 
 *
 *	Data type:	Tango::DevUShort
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TimingUnit::read_DelayLine1(Tango::Attribute &attr)
{
	DEBUG_STREAM << "TimingUnit::read_DelayLine1(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(TimingUnit::read_DelayLine1) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_DelayLine1_read);
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::read_DelayLine1
}
//--------------------------------------------------------
/**
 *	Write attribute DelayLine1 related method
 *	Description: 
 *
 *	Data type:	Tango::DevUShort
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TimingUnit::write_DelayLine1(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "TimingUnit::write_DelayLine1(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevUShort	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(TimingUnit::write_DelayLine1) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::write_DelayLine1
}
//--------------------------------------------------------
/**
 *	Read attribute DelayLine2 related method
 *	Description: 
 *
 *	Data type:	Tango::DevUShort
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TimingUnit::read_DelayLine2(Tango::Attribute &attr)
{
	DEBUG_STREAM << "TimingUnit::read_DelayLine2(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(TimingUnit::read_DelayLine2) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_DelayLine2_read);
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::read_DelayLine2
}
//--------------------------------------------------------
/**
 *	Write attribute DelayLine2 related method
 *	Description: 
 *
 *	Data type:	Tango::DevUShort
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TimingUnit::write_DelayLine2(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "TimingUnit::write_DelayLine2(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevUShort	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(TimingUnit::write_DelayLine2) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::write_DelayLine2
}
//--------------------------------------------------------
/**
 *	Read attribute DelayLine3 related method
 *	Description: 
 *
 *	Data type:	Tango::DevUShort
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TimingUnit::read_DelayLine3(Tango::Attribute &attr)
{
	DEBUG_STREAM << "TimingUnit::read_DelayLine3(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(TimingUnit::read_DelayLine3) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_DelayLine3_read);
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::read_DelayLine3
}
//--------------------------------------------------------
/**
 *	Write attribute DelayLine3 related method
 *	Description: 
 *
 *	Data type:	Tango::DevUShort
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TimingUnit::write_DelayLine3(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "TimingUnit::write_DelayLine3(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevUShort	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(TimingUnit::write_DelayLine3) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::write_DelayLine3
}
//--------------------------------------------------------
/**
 *	Read attribute DelayLine4 related method
 *	Description: 
 *
 *	Data type:	Tango::DevUShort
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TimingUnit::read_DelayLine4(Tango::Attribute &attr)
{
	DEBUG_STREAM << "TimingUnit::read_DelayLine4(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(TimingUnit::read_DelayLine4) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_DelayLine4_read);
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::read_DelayLine4
}
//--------------------------------------------------------
/**
 *	Write attribute DelayLine4 related method
 *	Description: 
 *
 *	Data type:	Tango::DevUShort
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TimingUnit::write_DelayLine4(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "TimingUnit::write_DelayLine4(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevUShort	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(TimingUnit::write_DelayLine4) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::write_DelayLine4
}
//--------------------------------------------------------
/**
 *	Read attribute DelayLine5 related method
 *	Description: 
 *
 *	Data type:	Tango::DevUShort
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TimingUnit::read_DelayLine5(Tango::Attribute &attr)
{
	DEBUG_STREAM << "TimingUnit::read_DelayLine5(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(TimingUnit::read_DelayLine5) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_DelayLine5_read);
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::read_DelayLine5
}
//--------------------------------------------------------
/**
 *	Write attribute DelayLine5 related method
 *	Description: 
 *
 *	Data type:	Tango::DevUShort
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TimingUnit::write_DelayLine5(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "TimingUnit::write_DelayLine5(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevUShort	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(TimingUnit::write_DelayLine5) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::write_DelayLine5
}
//--------------------------------------------------------
/**
 *	Read attribute Output_B0 related method
 *	Description: 
 *
 *	Data type:	Tango::DevEnum (Output_B0Enum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TimingUnit::read_Output_B0(Tango::Attribute &attr)
{
	DEBUG_STREAM << "TimingUnit::read_Output_B0(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(TimingUnit::read_Output_B0) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_Output_B0_read);
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::read_Output_B0
}
//--------------------------------------------------------
/**
 *	Write attribute Output_B0 related method
 *	Description: 
 *
 *	Data type:	Tango::DevEnum (Output_B0Enum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TimingUnit::write_Output_B0(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "TimingUnit::write_Output_B0(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Output_B0Enum	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(TimingUnit::write_Output_B0) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::write_Output_B0
}
//--------------------------------------------------------
/**
 *	Read attribute Output_B1 related method
 *	Description: 
 *
 *	Data type:	Tango::DevEnum (Output_B1Enum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TimingUnit::read_Output_B1(Tango::Attribute &attr)
{
	DEBUG_STREAM << "TimingUnit::read_Output_B1(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(TimingUnit::read_Output_B1) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_Output_B1_read);
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::read_Output_B1
}
//--------------------------------------------------------
/**
 *	Write attribute Output_B1 related method
 *	Description: 
 *
 *	Data type:	Tango::DevEnum (Output_B1Enum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TimingUnit::write_Output_B1(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "TimingUnit::write_Output_B1(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Output_B1Enum	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(TimingUnit::write_Output_B1) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::write_Output_B1
}
//--------------------------------------------------------
/**
 *	Read attribute Output_B2 related method
 *	Description: 
 *
 *	Data type:	Tango::DevEnum (Output_B2Enum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TimingUnit::read_Output_B2(Tango::Attribute &attr)
{
	DEBUG_STREAM << "TimingUnit::read_Output_B2(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(TimingUnit::read_Output_B2) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_Output_B2_read);
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::read_Output_B2
}
//--------------------------------------------------------
/**
 *	Write attribute Output_B2 related method
 *	Description: 
 *
 *	Data type:	Tango::DevEnum (Output_B2Enum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TimingUnit::write_Output_B2(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "TimingUnit::write_Output_B2(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Output_B2Enum	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(TimingUnit::write_Output_B2) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::write_Output_B2
}
//--------------------------------------------------------
/**
 *	Read attribute Output_B3 related method
 *	Description: 
 *
 *	Data type:	Tango::DevEnum (Output_B3Enum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TimingUnit::read_Output_B3(Tango::Attribute &attr)
{
	DEBUG_STREAM << "TimingUnit::read_Output_B3(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(TimingUnit::read_Output_B3) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_Output_B3_read);
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::read_Output_B3
}
//--------------------------------------------------------
/**
 *	Write attribute Output_B3 related method
 *	Description: 
 *
 *	Data type:	Tango::DevEnum (Output_B3Enum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TimingUnit::write_Output_B3(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "TimingUnit::write_Output_B3(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Output_B3Enum	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(TimingUnit::write_Output_B3) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::write_Output_B3
}
//--------------------------------------------------------
/**
 *	Read attribute Output_B4 related method
 *	Description: 
 *
 *	Data type:	Tango::DevEnum (Output_B4Enum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TimingUnit::read_Output_B4(Tango::Attribute &attr)
{
	DEBUG_STREAM << "TimingUnit::read_Output_B4(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(TimingUnit::read_Output_B4) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_Output_B4_read);
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::read_Output_B4
}
//--------------------------------------------------------
/**
 *	Write attribute Output_B4 related method
 *	Description: 
 *
 *	Data type:	Tango::DevEnum (Output_B4Enum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TimingUnit::write_Output_B4(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "TimingUnit::write_Output_B4(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Output_B4Enum	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(TimingUnit::write_Output_B4) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::write_Output_B4
}
//--------------------------------------------------------
/**
 *	Read attribute Output_B5 related method
 *	Description: 
 *
 *	Data type:	Tango::DevEnum (Output_B5Enum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TimingUnit::read_Output_B5(Tango::Attribute &attr)
{
	DEBUG_STREAM << "TimingUnit::read_Output_B5(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(TimingUnit::read_Output_B5) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_Output_B5_read);
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::read_Output_B5
}
//--------------------------------------------------------
/**
 *	Write attribute Output_B5 related method
 *	Description: 
 *
 *	Data type:	Tango::DevEnum (Output_B5Enum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TimingUnit::write_Output_B5(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "TimingUnit::write_Output_B5(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Output_B5Enum	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(TimingUnit::write_Output_B5) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::write_Output_B5
}
//--------------------------------------------------------
/**
 *	Read attribute Output_B6 related method
 *	Description: 
 *
 *	Data type:	Tango::DevEnum (Output_B6Enum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TimingUnit::read_Output_B6(Tango::Attribute &attr)
{
	DEBUG_STREAM << "TimingUnit::read_Output_B6(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(TimingUnit::read_Output_B6) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_Output_B6_read);
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::read_Output_B6
}
//--------------------------------------------------------
/**
 *	Write attribute Output_B6 related method
 *	Description: 
 *
 *	Data type:	Tango::DevEnum (Output_B6Enum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TimingUnit::write_Output_B6(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "TimingUnit::write_Output_B6(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Output_B6Enum	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(TimingUnit::write_Output_B6) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::write_Output_B6
}
//--------------------------------------------------------
/**
 *	Read attribute Output_B7 related method
 *	Description: 
 *
 *	Data type:	Tango::DevEnum (Output_B7Enum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TimingUnit::read_Output_B7(Tango::Attribute &attr)
{
	DEBUG_STREAM << "TimingUnit::read_Output_B7(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(TimingUnit::read_Output_B7) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_Output_B7_read);
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::read_Output_B7
}
//--------------------------------------------------------
/**
 *	Write attribute Output_B7 related method
 *	Description: 
 *
 *	Data type:	Tango::DevEnum (Output_B7Enum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TimingUnit::write_Output_B7(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "TimingUnit::write_Output_B7(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Output_B7Enum	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(TimingUnit::write_Output_B7) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::write_Output_B7
}
//--------------------------------------------------------
/**
 *	Read attribute Output_D0 related method
 *	Description: 
 *
 *	Data type:	Tango::DevEnum (Output_D0Enum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TimingUnit::read_Output_D0(Tango::Attribute &attr)
{
	DEBUG_STREAM << "TimingUnit::read_Output_D0(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(TimingUnit::read_Output_D0) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_Output_D0_read);
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::read_Output_D0
}
//--------------------------------------------------------
/**
 *	Write attribute Output_D0 related method
 *	Description: 
 *
 *	Data type:	Tango::DevEnum (Output_D0Enum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TimingUnit::write_Output_D0(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "TimingUnit::write_Output_D0(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Output_D0Enum	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(TimingUnit::write_Output_D0) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::write_Output_D0
}
//--------------------------------------------------------
/**
 *	Read attribute Output_D1 related method
 *	Description: 
 *
 *	Data type:	Tango::DevEnum (Output_D1Enum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TimingUnit::read_Output_D1(Tango::Attribute &attr)
{
	DEBUG_STREAM << "TimingUnit::read_Output_D1(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(TimingUnit::read_Output_D1) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_Output_D1_read);
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::read_Output_D1
}
//--------------------------------------------------------
/**
 *	Write attribute Output_D1 related method
 *	Description: 
 *
 *	Data type:	Tango::DevEnum (Output_D1Enum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TimingUnit::write_Output_D1(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "TimingUnit::write_Output_D1(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Output_D1Enum	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(TimingUnit::write_Output_D1) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::write_Output_D1
}
//--------------------------------------------------------
/**
 *	Read attribute Output_D2 related method
 *	Description: 
 *
 *	Data type:	Tango::DevEnum (Output_D2Enum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TimingUnit::read_Output_D2(Tango::Attribute &attr)
{
	DEBUG_STREAM << "TimingUnit::read_Output_D2(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(TimingUnit::read_Output_D2) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_Output_D2_read);
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::read_Output_D2
}
//--------------------------------------------------------
/**
 *	Write attribute Output_D2 related method
 *	Description: 
 *
 *	Data type:	Tango::DevEnum (Output_D2Enum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TimingUnit::write_Output_D2(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "TimingUnit::write_Output_D2(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Output_D2Enum	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(TimingUnit::write_Output_D2) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::write_Output_D2
}
//--------------------------------------------------------
/**
 *	Read attribute Output_D3 related method
 *	Description: 
 *
 *	Data type:	Tango::DevEnum (Output_D3Enum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TimingUnit::read_Output_D3(Tango::Attribute &attr)
{
	DEBUG_STREAM << "TimingUnit::read_Output_D3(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(TimingUnit::read_Output_D3) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_Output_D3_read);
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::read_Output_D3
}
//--------------------------------------------------------
/**
 *	Write attribute Output_D3 related method
 *	Description: 
 *
 *	Data type:	Tango::DevEnum (Output_D3Enum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TimingUnit::write_Output_D3(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "TimingUnit::write_Output_D3(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Output_D3Enum	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(TimingUnit::write_Output_D3) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::write_Output_D3
}

//--------------------------------------------------------
/**
 *	Method      : TimingUnit::add_dynamic_attributes()
 *	Description : Create the dynamic attributes if any
 *                for specified device.
 */
//--------------------------------------------------------
void TimingUnit::add_dynamic_attributes()
{
	/*----- PROTECTED REGION ID(TimingUnit::add_dynamic_attributes) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic attributes if any
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::add_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method      : TimingUnit::add_dynamic_commands()
 *	Description : Create the dynamic commands if any
 *                for specified device.
 */
//--------------------------------------------------------
void TimingUnit::add_dynamic_commands()
{
	/*----- PROTECTED REGION ID(TimingUnit::add_dynamic_commands) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic commands if any
	
	/*----- PROTECTED REGION END -----*/	//	TimingUnit::add_dynamic_commands
}

/*----- PROTECTED REGION ID(TimingUnit::namespace_ending) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	TimingUnit::namespace_ending
} //	namespace
