/*----- PROTECTED REGION ID(TANGOCamera.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        TANGOCamera.cpp
//
// description : C++ source for the TANGOCamera class and its commands.
//               The class is derived from Device. It represents the
//               CORBA servant object which will be accessed from the
//               network. All commands which can be executed on the
//               TANGOCamera are implemented in this file.
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <TANGOCamera.h>
#include <TANGOCameraClass.h>

/*----- PROTECTED REGION END -----*/	//	TANGOCamera.cpp

/**
 *  TANGOCamera class description:
 *    
 */

//================================================================
//  The following table gives the correspondence
//  between command and method names.
//
//  Command name      |  Method name
//================================================================
//  State             |  Inherited (no method)
//  Status            |  Inherited (no method)
//  StartAcquisition  |  start_acquisition
//  StopAcquisition   |  stop_acquisition
//  ManualTrigger     |  manual_trigger
//================================================================

//================================================================
//  Attributes managed are:
//================================================================
//  acquisitionFrameRate         |  Tango::DevULong64	Scalar
//  acquisitionFrameRateEnable   |  Tango::DevBoolean	Scalar
//  acquisitionMode              |  Tango::DevEnum	Scalar
//  deviceLinkCurrentThroughput  |  Tango::DevULong64	Scalar
//  deviceLinkThroughputLimit    |  Tango::DevULong64	Scalar
//  exposureAuto                 |  Tango::DevEnum	Scalar
//  exposureMode                 |  Tango::DevEnum	Scalar
//  exposureTimeInMicroseconds   |  Tango::DevULong64	Scalar
//  gain                         |  Tango::DevULong64	Scalar
//  gainAuto                     |  Tango::DevEnum	Scalar
//  pixelFormat                  |  Tango::DevEnum	Scalar
//  triggerActivation            |  Tango::DevEnum	Scalar
//  triggerDelayInMicroseconds   |  Tango::DevULong64	Scalar
//  triggerSelector              |  Tango::DevEnum	Scalar
//  triggerSource                |  Tango::DevEnum	Scalar
//  triggerMode                  |  Tango::DevBoolean	Scalar
//  roi_xmin                     |  Tango::DevULong64	Scalar
//  roi_xmax                     |  Tango::DevULong64	Scalar
//  roi_ymin                     |  Tango::DevULong64	Scalar
//  roi_ymax                     |  Tango::DevULong64	Scalar
//================================================================

namespace TANGOCamera_ns
{
/*----- PROTECTED REGION ID(TANGOCamera::namespace_starting) ENABLED START -----*/

//	static initializations

/*----- PROTECTED REGION END -----*/	//	TANGOCamera::namespace_starting

//--------------------------------------------------------
/**
 *	Method      : TANGOCamera::TANGOCamera()
 *	Description : Constructors for a Tango device
 *                implementing the classTANGOCamera
 */
//--------------------------------------------------------
TANGOCamera::TANGOCamera(Tango::DeviceClass *cl, string &s)
 : TANGO_BASE_CLASS(cl, s.c_str())
{
	/*----- PROTECTED REGION ID(TANGOCamera::constructor_1) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::constructor_1
}
//--------------------------------------------------------
TANGOCamera::TANGOCamera(Tango::DeviceClass *cl, const char *s)
 : TANGO_BASE_CLASS(cl, s)
{
	/*----- PROTECTED REGION ID(TANGOCamera::constructor_2) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::constructor_2
}
//--------------------------------------------------------
TANGOCamera::TANGOCamera(Tango::DeviceClass *cl, const char *s, const char *d)
 : TANGO_BASE_CLASS(cl, s, d)
{
	/*----- PROTECTED REGION ID(TANGOCamera::constructor_3) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::constructor_3
}

//--------------------------------------------------------
/**
 *	Method      : TANGOCamera::delete_device()
 *	Description : will be called at device destruction or at init command
 */
//--------------------------------------------------------
void TANGOCamera::delete_device()
{
	DEBUG_STREAM << "TANGOCamera::delete_device() " << device_name << endl;
	/*----- PROTECTED REGION ID(TANGOCamera::delete_device) ENABLED START -----*/
	
	//	Delete device allocated objects
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::delete_device
	delete[] attr_acquisitionFrameRate_read;
	delete[] attr_acquisitionFrameRateEnable_read;
	delete[] attr_acquisitionMode_read;
	delete[] attr_deviceLinkCurrentThroughput_read;
	delete[] attr_deviceLinkThroughputLimit_read;
	delete[] attr_exposureAuto_read;
	delete[] attr_exposureMode_read;
	delete[] attr_exposureTimeInMicroseconds_read;
	delete[] attr_gain_read;
	delete[] attr_gainAuto_read;
	delete[] attr_pixelFormat_read;
	delete[] attr_triggerActivation_read;
	delete[] attr_triggerDelayInMicroseconds_read;
	delete[] attr_triggerSelector_read;
	delete[] attr_triggerSource_read;
	delete[] attr_triggerMode_read;
	delete[] attr_roi_xmin_read;
	delete[] attr_roi_xmax_read;
	delete[] attr_roi_ymin_read;
	delete[] attr_roi_ymax_read;
}

//--------------------------------------------------------
/**
 *	Method      : TANGOCamera::init_device()
 *	Description : will be called at device initialization.
 */
//--------------------------------------------------------
void TANGOCamera::init_device()
{
	DEBUG_STREAM << "TANGOCamera::init_device() create device " << device_name << endl;
	/*----- PROTECTED REGION ID(TANGOCamera::init_device_before) ENABLED START -----*/
	
	//	Initialization before get_device_property() call
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::init_device_before
	

	//	Get the device properties from database
	get_device_property();
	
	attr_acquisitionFrameRate_read = new Tango::DevULong64[1];
	attr_acquisitionFrameRateEnable_read = new Tango::DevBoolean[1];
	attr_acquisitionMode_read = new acquisitionModeEnum[1];
	attr_deviceLinkCurrentThroughput_read = new Tango::DevULong64[1];
	attr_deviceLinkThroughputLimit_read = new Tango::DevULong64[1];
	attr_exposureAuto_read = new exposureAutoEnum[1];
	attr_exposureMode_read = new exposureModeEnum[1];
	attr_exposureTimeInMicroseconds_read = new Tango::DevULong64[1];
	attr_gain_read = new Tango::DevULong64[1];
	attr_gainAuto_read = new gainAutoEnum[1];
	attr_pixelFormat_read = new pixelFormatEnum[1];
	attr_triggerActivation_read = new triggerActivationEnum[1];
	attr_triggerDelayInMicroseconds_read = new Tango::DevULong64[1];
	attr_triggerSelector_read = new triggerSelectorEnum[1];
	attr_triggerSource_read = new triggerSourceEnum[1];
	attr_triggerMode_read = new Tango::DevBoolean[1];
	attr_roi_xmin_read = new Tango::DevULong64[1];
	attr_roi_xmax_read = new Tango::DevULong64[1];
	attr_roi_ymin_read = new Tango::DevULong64[1];
	attr_roi_ymax_read = new Tango::DevULong64[1];
	//	No longer if mandatory property not set. 
	if (mandatoryNotDefined)
		return;

	/*----- PROTECTED REGION ID(TANGOCamera::init_device) ENABLED START -----*/
	
	//	Initialize device
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::init_device
}

//--------------------------------------------------------
/**
 *	Method      : TANGOCamera::get_device_property()
 *	Description : Read database to initialize property data members.
 */
//--------------------------------------------------------
void TANGOCamera::get_device_property()
{
	/*----- PROTECTED REGION ID(TANGOCamera::get_device_property_before) ENABLED START -----*/
	
	//	Initialize property data members
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::get_device_property_before

	mandatoryNotDefined = false;

	//	Read device properties from database.
	Tango::DbData	dev_prop;
	dev_prop.push_back(Tango::DbDatum("ImageMaxWidth"));
	dev_prop.push_back(Tango::DbDatum("ImageMaxHeight"));
	dev_prop.push_back(Tango::DbDatum("DeviceVendorName"));
	dev_prop.push_back(Tango::DbDatum("IPAdress"));

	//	is there at least one property to be read ?
	if (dev_prop.size()>0)
	{
		//	Call database and extract values
		if (Tango::Util::instance()->_UseDb==true)
			get_db_device()->get_property(dev_prop);
	
		//	get instance on TANGOCameraClass to get class property
		Tango::DbDatum	def_prop, cl_prop;
		TANGOCameraClass	*ds_class =
			(static_cast<TANGOCameraClass *>(get_device_class()));
		int	i = -1;

		//	Try to initialize ImageMaxWidth from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  imageMaxWidth;
		else {
			//	Try to initialize ImageMaxWidth from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  imageMaxWidth;
		}
		//	And try to extract ImageMaxWidth value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  imageMaxWidth;
		//	Property StartDsPath is mandatory, check if has been defined in database.
		check_mandatory_property(cl_prop, dev_prop[i]);

		//	Try to initialize ImageMaxHeight from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  imageMaxHeight;
		else {
			//	Try to initialize ImageMaxHeight from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  imageMaxHeight;
		}
		//	And try to extract ImageMaxHeight value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  imageMaxHeight;
		//	Property StartDsPath is mandatory, check if has been defined in database.
		check_mandatory_property(cl_prop, dev_prop[i]);

		//	Try to initialize DeviceVendorName from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  deviceVendorName;
		else {
			//	Try to initialize DeviceVendorName from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  deviceVendorName;
		}
		//	And try to extract DeviceVendorName value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  deviceVendorName;
		//	Property StartDsPath is mandatory, check if has been defined in database.
		check_mandatory_property(cl_prop, dev_prop[i]);

		//	Try to initialize IPAdress from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  iPAdress;
		else {
			//	Try to initialize IPAdress from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  iPAdress;
		}
		//	And try to extract IPAdress value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  iPAdress;
		//	Property StartDsPath is mandatory, check if has been defined in database.
		check_mandatory_property(cl_prop, dev_prop[i]);

	}

	/*----- PROTECTED REGION ID(TANGOCamera::get_device_property_after) ENABLED START -----*/
	
	//	Check device property data members init
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::get_device_property_after
}
//--------------------------------------------------------
/**
 *	Method      : TANGOCamera::check_mandatory_property()
 *	Description : For mandatory properties check if defined in database.
 */
//--------------------------------------------------------
void TANGOCamera::check_mandatory_property(Tango::DbDatum &class_prop, Tango::DbDatum &dev_prop)
{
	//	Check if all properties are empty
	if (class_prop.is_empty() && dev_prop.is_empty())
	{
		TangoSys_OMemStream	tms;
		tms << endl <<"Property \'" << dev_prop.name;
		if (Tango::Util::instance()->_UseDb==true)
			tms << "\' is mandatory but not defined in database";
		else
			tms << "\' is mandatory but cannot be defined without database";
		append_status(tms.str());
		mandatoryNotDefined = true;
		/*----- PROTECTED REGION ID(TANGOCamera::check_mandatory_property) ENABLED START -----*/
		cerr << tms.str() << " for " << device_name << endl;
		
		/*----- PROTECTED REGION END -----*/	//	TANGOCamera::check_mandatory_property
	}
}


//--------------------------------------------------------
/**
 *	Method      : TANGOCamera::always_executed_hook()
 *	Description : method always executed before any command is executed
 */
//--------------------------------------------------------
void TANGOCamera::always_executed_hook()
{
	DEBUG_STREAM << "TANGOCamera::always_executed_hook()  " << device_name << endl;
	if (mandatoryNotDefined)
	{
		Tango::Except::throw_exception(
					(const char *)"PROPERTY_NOT_SET",
					get_status().c_str(),
					(const char *)"TANGOCamera::always_executed_hook()");
	}
	/*----- PROTECTED REGION ID(TANGOCamera::always_executed_hook) ENABLED START -----*/
	
	//	code always executed before all requests
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::always_executed_hook
}

//--------------------------------------------------------
/**
 *	Method      : TANGOCamera::read_attr_hardware()
 *	Description : Hardware acquisition for attributes
 */
//--------------------------------------------------------
void TANGOCamera::read_attr_hardware(TANGO_UNUSED(vector<long> &attr_list))
{
	DEBUG_STREAM << "TANGOCamera::read_attr_hardware(vector<long> &attr_list) entering... " << endl;
	/*----- PROTECTED REGION ID(TANGOCamera::read_attr_hardware) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::read_attr_hardware
}
//--------------------------------------------------------
/**
 *	Method      : TANGOCamera::write_attr_hardware()
 *	Description : Hardware writing for attributes
 */
//--------------------------------------------------------
void TANGOCamera::write_attr_hardware(TANGO_UNUSED(vector<long> &attr_list))
{
	DEBUG_STREAM << "TANGOCamera::write_attr_hardware(vector<long> &attr_list) entering... " << endl;
	/*----- PROTECTED REGION ID(TANGOCamera::write_attr_hardware) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::write_attr_hardware
}

//--------------------------------------------------------
/**
 *	Read attribute acquisitionFrameRate related method
 *	Description: 
 *
 *	Data type:	Tango::DevULong64
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TANGOCamera::read_acquisitionFrameRate(Tango::Attribute &attr)
{
	DEBUG_STREAM << "TANGOCamera::read_acquisitionFrameRate(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(TANGOCamera::read_acquisitionFrameRate) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_acquisitionFrameRate_read);
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::read_acquisitionFrameRate
}
//--------------------------------------------------------
/**
 *	Write attribute acquisitionFrameRate related method
 *	Description: 
 *
 *	Data type:	Tango::DevULong64
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TANGOCamera::write_acquisitionFrameRate(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "TANGOCamera::write_acquisitionFrameRate(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevULong64	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(TANGOCamera::write_acquisitionFrameRate) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::write_acquisitionFrameRate
}
//--------------------------------------------------------
/**
 *	Read attribute acquisitionFrameRateEnable related method
 *	Description: 
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TANGOCamera::read_acquisitionFrameRateEnable(Tango::Attribute &attr)
{
	DEBUG_STREAM << "TANGOCamera::read_acquisitionFrameRateEnable(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(TANGOCamera::read_acquisitionFrameRateEnable) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_acquisitionFrameRateEnable_read);
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::read_acquisitionFrameRateEnable
}
//--------------------------------------------------------
/**
 *	Write attribute acquisitionFrameRateEnable related method
 *	Description: 
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TANGOCamera::write_acquisitionFrameRateEnable(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "TANGOCamera::write_acquisitionFrameRateEnable(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevBoolean	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(TANGOCamera::write_acquisitionFrameRateEnable) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::write_acquisitionFrameRateEnable
}
//--------------------------------------------------------
/**
 *	Read attribute acquisitionMode related method
 *	Description: 
 *
 *	Data type:	Tango::DevEnum (acquisitionModeEnum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TANGOCamera::read_acquisitionMode(Tango::Attribute &attr)
{
	DEBUG_STREAM << "TANGOCamera::read_acquisitionMode(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(TANGOCamera::read_acquisitionMode) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_acquisitionMode_read);
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::read_acquisitionMode
}
//--------------------------------------------------------
/**
 *	Write attribute acquisitionMode related method
 *	Description: 
 *
 *	Data type:	Tango::DevEnum (acquisitionModeEnum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TANGOCamera::write_acquisitionMode(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "TANGOCamera::write_acquisitionMode(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	acquisitionModeEnum	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(TANGOCamera::write_acquisitionMode) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::write_acquisitionMode
}
//--------------------------------------------------------
/**
 *	Read attribute deviceLinkCurrentThroughput related method
 *	Description: 
 *
 *	Data type:	Tango::DevULong64
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TANGOCamera::read_deviceLinkCurrentThroughput(Tango::Attribute &attr)
{
	DEBUG_STREAM << "TANGOCamera::read_deviceLinkCurrentThroughput(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(TANGOCamera::read_deviceLinkCurrentThroughput) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_deviceLinkCurrentThroughput_read);
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::read_deviceLinkCurrentThroughput
}
//--------------------------------------------------------
/**
 *	Read attribute deviceLinkThroughputLimit related method
 *	Description: 
 *
 *	Data type:	Tango::DevULong64
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TANGOCamera::read_deviceLinkThroughputLimit(Tango::Attribute &attr)
{
	DEBUG_STREAM << "TANGOCamera::read_deviceLinkThroughputLimit(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(TANGOCamera::read_deviceLinkThroughputLimit) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_deviceLinkThroughputLimit_read);
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::read_deviceLinkThroughputLimit
}
//--------------------------------------------------------
/**
 *	Write attribute deviceLinkThroughputLimit related method
 *	Description: 
 *
 *	Data type:	Tango::DevULong64
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TANGOCamera::write_deviceLinkThroughputLimit(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "TANGOCamera::write_deviceLinkThroughputLimit(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevULong64	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(TANGOCamera::write_deviceLinkThroughputLimit) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::write_deviceLinkThroughputLimit
}
//--------------------------------------------------------
/**
 *	Read attribute exposureAuto related method
 *	Description: 
 *
 *	Data type:	Tango::DevEnum (exposureAutoEnum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TANGOCamera::read_exposureAuto(Tango::Attribute &attr)
{
	DEBUG_STREAM << "TANGOCamera::read_exposureAuto(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(TANGOCamera::read_exposureAuto) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_exposureAuto_read);
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::read_exposureAuto
}
//--------------------------------------------------------
/**
 *	Write attribute exposureAuto related method
 *	Description: 
 *
 *	Data type:	Tango::DevEnum (exposureAutoEnum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TANGOCamera::write_exposureAuto(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "TANGOCamera::write_exposureAuto(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	exposureAutoEnum	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(TANGOCamera::write_exposureAuto) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::write_exposureAuto
}
//--------------------------------------------------------
/**
 *	Read attribute exposureMode related method
 *	Description: 
 *
 *	Data type:	Tango::DevEnum (exposureModeEnum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TANGOCamera::read_exposureMode(Tango::Attribute &attr)
{
	DEBUG_STREAM << "TANGOCamera::read_exposureMode(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(TANGOCamera::read_exposureMode) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_exposureMode_read);
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::read_exposureMode
}
//--------------------------------------------------------
/**
 *	Write attribute exposureMode related method
 *	Description: 
 *
 *	Data type:	Tango::DevEnum (exposureModeEnum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TANGOCamera::write_exposureMode(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "TANGOCamera::write_exposureMode(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	exposureModeEnum	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(TANGOCamera::write_exposureMode) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::write_exposureMode
}
//--------------------------------------------------------
/**
 *	Read attribute exposureTimeInMicroseconds related method
 *	Description: 
 *
 *	Data type:	Tango::DevULong64
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TANGOCamera::read_exposureTimeInMicroseconds(Tango::Attribute &attr)
{
	DEBUG_STREAM << "TANGOCamera::read_exposureTimeInMicroseconds(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(TANGOCamera::read_exposureTimeInMicroseconds) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_exposureTimeInMicroseconds_read);
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::read_exposureTimeInMicroseconds
}
//--------------------------------------------------------
/**
 *	Write attribute exposureTimeInMicroseconds related method
 *	Description: 
 *
 *	Data type:	Tango::DevULong64
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TANGOCamera::write_exposureTimeInMicroseconds(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "TANGOCamera::write_exposureTimeInMicroseconds(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevULong64	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(TANGOCamera::write_exposureTimeInMicroseconds) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::write_exposureTimeInMicroseconds
}
//--------------------------------------------------------
/**
 *	Read attribute gain related method
 *	Description: 
 *
 *	Data type:	Tango::DevULong64
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TANGOCamera::read_gain(Tango::Attribute &attr)
{
	DEBUG_STREAM << "TANGOCamera::read_gain(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(TANGOCamera::read_gain) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_gain_read);
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::read_gain
}
//--------------------------------------------------------
/**
 *	Write attribute gain related method
 *	Description: 
 *
 *	Data type:	Tango::DevULong64
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TANGOCamera::write_gain(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "TANGOCamera::write_gain(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevULong64	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(TANGOCamera::write_gain) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::write_gain
}
//--------------------------------------------------------
/**
 *	Read attribute gainAuto related method
 *	Description: 
 *
 *	Data type:	Tango::DevEnum (gainAutoEnum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TANGOCamera::read_gainAuto(Tango::Attribute &attr)
{
	DEBUG_STREAM << "TANGOCamera::read_gainAuto(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(TANGOCamera::read_gainAuto) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_gainAuto_read);
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::read_gainAuto
}
//--------------------------------------------------------
/**
 *	Write attribute gainAuto related method
 *	Description: 
 *
 *	Data type:	Tango::DevEnum (gainAutoEnum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TANGOCamera::write_gainAuto(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "TANGOCamera::write_gainAuto(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	gainAutoEnum	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(TANGOCamera::write_gainAuto) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::write_gainAuto
}
//--------------------------------------------------------
/**
 *	Read attribute pixelFormat related method
 *	Description: 
 *
 *	Data type:	Tango::DevEnum (pixelFormatEnum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TANGOCamera::read_pixelFormat(Tango::Attribute &attr)
{
	DEBUG_STREAM << "TANGOCamera::read_pixelFormat(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(TANGOCamera::read_pixelFormat) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_pixelFormat_read);
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::read_pixelFormat
}
//--------------------------------------------------------
/**
 *	Write attribute pixelFormat related method
 *	Description: 
 *
 *	Data type:	Tango::DevEnum (pixelFormatEnum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TANGOCamera::write_pixelFormat(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "TANGOCamera::write_pixelFormat(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	pixelFormatEnum	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(TANGOCamera::write_pixelFormat) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::write_pixelFormat
}
//--------------------------------------------------------
/**
 *	Read attribute triggerActivation related method
 *	Description: 
 *
 *	Data type:	Tango::DevEnum (triggerActivationEnum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TANGOCamera::read_triggerActivation(Tango::Attribute &attr)
{
	DEBUG_STREAM << "TANGOCamera::read_triggerActivation(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(TANGOCamera::read_triggerActivation) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_triggerActivation_read);
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::read_triggerActivation
}
//--------------------------------------------------------
/**
 *	Write attribute triggerActivation related method
 *	Description: 
 *
 *	Data type:	Tango::DevEnum (triggerActivationEnum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TANGOCamera::write_triggerActivation(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "TANGOCamera::write_triggerActivation(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	triggerActivationEnum	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(TANGOCamera::write_triggerActivation) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::write_triggerActivation
}
//--------------------------------------------------------
/**
 *	Read attribute triggerDelayInMicroseconds related method
 *	Description: 
 *
 *	Data type:	Tango::DevULong64
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TANGOCamera::read_triggerDelayInMicroseconds(Tango::Attribute &attr)
{
	DEBUG_STREAM << "TANGOCamera::read_triggerDelayInMicroseconds(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(TANGOCamera::read_triggerDelayInMicroseconds) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_triggerDelayInMicroseconds_read);
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::read_triggerDelayInMicroseconds
}
//--------------------------------------------------------
/**
 *	Write attribute triggerDelayInMicroseconds related method
 *	Description: 
 *
 *	Data type:	Tango::DevULong64
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TANGOCamera::write_triggerDelayInMicroseconds(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "TANGOCamera::write_triggerDelayInMicroseconds(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevULong64	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(TANGOCamera::write_triggerDelayInMicroseconds) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::write_triggerDelayInMicroseconds
}
//--------------------------------------------------------
/**
 *	Read attribute triggerSelector related method
 *	Description: 
 *
 *	Data type:	Tango::DevEnum (triggerSelectorEnum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TANGOCamera::read_triggerSelector(Tango::Attribute &attr)
{
	DEBUG_STREAM << "TANGOCamera::read_triggerSelector(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(TANGOCamera::read_triggerSelector) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_triggerSelector_read);
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::read_triggerSelector
}
//--------------------------------------------------------
/**
 *	Write attribute triggerSelector related method
 *	Description: 
 *
 *	Data type:	Tango::DevEnum (triggerSelectorEnum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TANGOCamera::write_triggerSelector(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "TANGOCamera::write_triggerSelector(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	triggerSelectorEnum	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(TANGOCamera::write_triggerSelector) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::write_triggerSelector
}
//--------------------------------------------------------
/**
 *	Read attribute triggerSource related method
 *	Description: 
 *
 *	Data type:	Tango::DevEnum (triggerSourceEnum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TANGOCamera::read_triggerSource(Tango::Attribute &attr)
{
	DEBUG_STREAM << "TANGOCamera::read_triggerSource(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(TANGOCamera::read_triggerSource) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_triggerSource_read);
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::read_triggerSource
}
//--------------------------------------------------------
/**
 *	Write attribute triggerSource related method
 *	Description: 
 *
 *	Data type:	Tango::DevEnum (triggerSourceEnum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TANGOCamera::write_triggerSource(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "TANGOCamera::write_triggerSource(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	triggerSourceEnum	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(TANGOCamera::write_triggerSource) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::write_triggerSource
}
//--------------------------------------------------------
/**
 *	Read attribute triggerMode related method
 *	Description: 
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TANGOCamera::read_triggerMode(Tango::Attribute &attr)
{
	DEBUG_STREAM << "TANGOCamera::read_triggerMode(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(TANGOCamera::read_triggerMode) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_triggerMode_read);
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::read_triggerMode
}
//--------------------------------------------------------
/**
 *	Write attribute triggerMode related method
 *	Description: 
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TANGOCamera::write_triggerMode(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "TANGOCamera::write_triggerMode(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevBoolean	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(TANGOCamera::write_triggerMode) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::write_triggerMode
}
//--------------------------------------------------------
/**
 *	Read attribute roi_xmin related method
 *	Description: 
 *
 *	Data type:	Tango::DevULong64
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TANGOCamera::read_roi_xmin(Tango::Attribute &attr)
{
	DEBUG_STREAM << "TANGOCamera::read_roi_xmin(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(TANGOCamera::read_roi_xmin) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_roi_xmin_read);
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::read_roi_xmin
}
//--------------------------------------------------------
/**
 *	Write attribute roi_xmin related method
 *	Description: 
 *
 *	Data type:	Tango::DevULong64
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TANGOCamera::write_roi_xmin(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "TANGOCamera::write_roi_xmin(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevULong64	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(TANGOCamera::write_roi_xmin) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::write_roi_xmin
}
//--------------------------------------------------------
/**
 *	Read attribute roi_xmax related method
 *	Description: 
 *
 *	Data type:	Tango::DevULong64
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TANGOCamera::read_roi_xmax(Tango::Attribute &attr)
{
	DEBUG_STREAM << "TANGOCamera::read_roi_xmax(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(TANGOCamera::read_roi_xmax) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_roi_xmax_read);
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::read_roi_xmax
}
//--------------------------------------------------------
/**
 *	Write attribute roi_xmax related method
 *	Description: 
 *
 *	Data type:	Tango::DevULong64
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TANGOCamera::write_roi_xmax(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "TANGOCamera::write_roi_xmax(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevULong64	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(TANGOCamera::write_roi_xmax) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::write_roi_xmax
}
//--------------------------------------------------------
/**
 *	Read attribute roi_ymin related method
 *	Description: 
 *
 *	Data type:	Tango::DevULong64
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TANGOCamera::read_roi_ymin(Tango::Attribute &attr)
{
	DEBUG_STREAM << "TANGOCamera::read_roi_ymin(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(TANGOCamera::read_roi_ymin) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_roi_ymin_read);
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::read_roi_ymin
}
//--------------------------------------------------------
/**
 *	Write attribute roi_ymin related method
 *	Description: 
 *
 *	Data type:	Tango::DevULong64
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TANGOCamera::write_roi_ymin(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "TANGOCamera::write_roi_ymin(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevULong64	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(TANGOCamera::write_roi_ymin) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::write_roi_ymin
}
//--------------------------------------------------------
/**
 *	Read attribute roi_ymax related method
 *	Description: 
 *
 *	Data type:	Tango::DevULong64
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TANGOCamera::read_roi_ymax(Tango::Attribute &attr)
{
	DEBUG_STREAM << "TANGOCamera::read_roi_ymax(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(TANGOCamera::read_roi_ymax) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_roi_ymax_read);
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::read_roi_ymax
}
//--------------------------------------------------------
/**
 *	Write attribute roi_ymax related method
 *	Description: 
 *
 *	Data type:	Tango::DevULong64
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TANGOCamera::write_roi_ymax(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "TANGOCamera::write_roi_ymax(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevULong64	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(TANGOCamera::write_roi_ymax) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::write_roi_ymax
}

//--------------------------------------------------------
/**
 *	Method      : TANGOCamera::add_dynamic_attributes()
 *	Description : Create the dynamic attributes if any
 *                for specified device.
 */
//--------------------------------------------------------
void TANGOCamera::add_dynamic_attributes()
{
	/*----- PROTECTED REGION ID(TANGOCamera::add_dynamic_attributes) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic attributes if any
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::add_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Command StartAcquisition related method
 *	Description: Start image acquisition
 *
 */
//--------------------------------------------------------
void TANGOCamera::start_acquisition()
{
	DEBUG_STREAM << "TANGOCamera::StartAcquisition()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(TANGOCamera::start_acquisition) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::start_acquisition
}
//--------------------------------------------------------
/**
 *	Command StopAcquisition related method
 *	Description: Stop image acquisition
 *
 */
//--------------------------------------------------------
void TANGOCamera::stop_acquisition()
{
	DEBUG_STREAM << "TANGOCamera::StopAcquisition()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(TANGOCamera::stop_acquisition) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::stop_acquisition
}
//--------------------------------------------------------
/**
 *	Command ManualTrigger related method
 *	Description: Reset camera if in FAULT state
 *
 */
//--------------------------------------------------------
void TANGOCamera::manual_trigger()
{
	DEBUG_STREAM << "TANGOCamera::ManualTrigger()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(TANGOCamera::manual_trigger) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::manual_trigger
}
//--------------------------------------------------------
/**
 *	Method      : TANGOCamera::add_dynamic_commands()
 *	Description : Create the dynamic commands if any
 *                for specified device.
 */
//--------------------------------------------------------
void TANGOCamera::add_dynamic_commands()
{
	/*----- PROTECTED REGION ID(TANGOCamera::add_dynamic_commands) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic commands if any
	
	/*----- PROTECTED REGION END -----*/	//	TANGOCamera::add_dynamic_commands
}

/*----- PROTECTED REGION ID(TANGOCamera::namespace_ending) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	TANGOCamera::namespace_ending
} //	namespace
