/*----- PROTECTED REGION ID(StanfordDG645ChannelClass.h) ENABLED START -----*/
//=============================================================================
//
// file :        StanfordDG645ChannelClass.h
//
// description : Include for the StanfordDG645Channel root class.
//               This class is the singleton class for
//                the StanfordDG645Channel device class.
//               It contains all properties and methods which the 
//               StanfordDG645Channel requires only once e.g. the commands.
//
// project :     StanfordDG645Channel
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef StanfordDG645ChannelClass_H
#define StanfordDG645ChannelClass_H

#include <tango.h>
#include <StanfordDG645Channel.h>


/*----- PROTECTED REGION END -----*/	//	StanfordDG645ChannelClass.h


namespace StanfordDG645Channel_ns
{
/*----- PROTECTED REGION ID(StanfordDG645ChannelClass::classes for dynamic creation) ENABLED START -----*/


/*----- PROTECTED REGION END -----*/	//	StanfordDG645ChannelClass::classes for dynamic creation

//=========================================
//	Define classes for attributes
//=========================================
//	Attribute OutputAmplitude class definition
class OutputAmplitudeAttrib: public Tango::Attr
{
public:
	OutputAmplitudeAttrib():Attr("OutputAmplitude",
			Tango::DEV_FLOAT, Tango::READ_WRITE) {};
	~OutputAmplitudeAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<StanfordDG645Channel *>(dev))->read_OutputAmplitude(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<StanfordDG645Channel *>(dev))->write_OutputAmplitude(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<StanfordDG645Channel *>(dev))->is_OutputAmplitude_allowed(ty);}
};

//	Attribute OutputOffset class definition
class OutputOffsetAttrib: public Tango::Attr
{
public:
	OutputOffsetAttrib():Attr("OutputOffset",
			Tango::DEV_FLOAT, Tango::READ_WRITE) {};
	~OutputOffsetAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<StanfordDG645Channel *>(dev))->read_OutputOffset(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<StanfordDG645Channel *>(dev))->write_OutputOffset(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<StanfordDG645Channel *>(dev))->is_OutputOffset_allowed(ty);}
};

//	Attribute OutputWidth class definition
class OutputWidthAttrib: public Tango::Attr
{
public:
	OutputWidthAttrib():Attr("OutputWidth",
			Tango::DEV_DOUBLE, Tango::READ_WRITE) {};
	~OutputWidthAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<StanfordDG645Channel *>(dev))->read_OutputWidth(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<StanfordDG645Channel *>(dev))->write_OutputWidth(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<StanfordDG645Channel *>(dev))->is_OutputWidth_allowed(ty);}
};

//	Attribute TriggerDelay class definition
class TriggerDelayAttrib: public Tango::Attr
{
public:
	TriggerDelayAttrib():Attr("TriggerDelay",
			Tango::DEV_DOUBLE, Tango::READ_WRITE) {};
	~TriggerDelayAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<StanfordDG645Channel *>(dev))->read_TriggerDelay(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<StanfordDG645Channel *>(dev))->write_TriggerDelay(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<StanfordDG645Channel *>(dev))->is_TriggerDelay_allowed(ty);}
};


//=========================================
//	Define classes for dynamic attributes
//=========================================
//	Attribute TriggerPrescale class definition
class TriggerPrescaleAttrib: public Tango::Attr
{
public:
	TriggerPrescaleAttrib(const string &att_name):Attr(att_name.c_str(), 
			Tango::DEV_ULONG, Tango::READ_WRITE) {};
	~TriggerPrescaleAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<StanfordDG645Channel *>(dev))->read_TriggerPrescale(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<StanfordDG645Channel *>(dev))->write_TriggerPrescale(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<StanfordDG645Channel *>(dev))->is_TriggerPrescale_allowed(ty);}
};

//	Attribute TriggerPhase class definition
class TriggerPhaseAttrib: public Tango::Attr
{
public:
	TriggerPhaseAttrib(const string &att_name):Attr(att_name.c_str(), 
			Tango::DEV_ULONG, Tango::READ_WRITE) {};
	~TriggerPhaseAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<StanfordDG645Channel *>(dev))->read_TriggerPhase(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<StanfordDG645Channel *>(dev))->write_TriggerPhase(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<StanfordDG645Channel *>(dev))->is_TriggerPhase_allowed(ty);}
};

//	Attribute BurstMode class definition
class BurstModeAttrib: public Tango::Attr
{
public:
	BurstModeAttrib(const string &att_name):Attr(att_name.c_str(), 
			Tango::DEV_BOOLEAN, Tango::READ_WRITE) {};
	~BurstModeAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<StanfordDG645Channel *>(dev))->read_BurstMode(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<StanfordDG645Channel *>(dev))->write_BurstMode(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<StanfordDG645Channel *>(dev))->is_BurstMode_allowed(ty);}
};


/**
 *	The StanfordDG645ChannelClass singleton definition
 */

#ifdef _TG_WINDOWS_
class __declspec(dllexport)  StanfordDG645ChannelClass : public Tango::DeviceClass
#else
class StanfordDG645ChannelClass : public Tango::DeviceClass
#endif
{
	/*----- PROTECTED REGION ID(StanfordDG645ChannelClass::Additionnal DServer data members) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	StanfordDG645ChannelClass::Additionnal DServer data members

	public:
		//	write class properties data members
		Tango::DbData	cl_prop;
		Tango::DbData	cl_def_prop;
		Tango::DbData	dev_def_prop;
	
		//	Method prototypes
		static StanfordDG645ChannelClass *init(const char *);
		static StanfordDG645ChannelClass *instance();
		~StanfordDG645ChannelClass();
		Tango::DbDatum	get_class_property(string &);
		Tango::DbDatum	get_default_device_property(string &);
		Tango::DbDatum	get_default_class_property(string &);
	
	protected:
		StanfordDG645ChannelClass(string &);
		static StanfordDG645ChannelClass *_instance;
		void command_factory();
		void attribute_factory(vector<Tango::Attr *> &);
		void pipe_factory();
		void write_class_property();
		void set_default_property();
		void get_class_property();
		string get_cvstag();
		string get_cvsroot();
	
	private:
		void device_factory(const Tango::DevVarStringArray *);
		void create_static_attribute_list(vector<Tango::Attr *> &);
		void erase_dynamic_attributes(const Tango::DevVarStringArray *,vector<Tango::Attr *> &);
		vector<string>	defaultAttList;
		Tango::Attr *get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname);
};

}	//	End of namespace

#endif   //	StanfordDG645Channel_H
